var suggestions = {
    "suggestions": {
        "1": "Fayence-Porzellanvasen",
        "2": "Besuch Samstag im Februar",
        "3": "Fr\u00fchling - Tulpen",
        "4": "Freilandnelken aus San Remo",
        "5": "Auswahl an mediterranen Kr\u00e4utern",
        "6": "spontan Blumen schenken? ",
        "7": "Porzellanvasen Maurizio",
        "8": "Gutscheine",
        "10": "Sommerfest",
        "11": "Schulthess-Kerzen - Fr\u00fchlingsd\u00fcfte",
        "12": "Schweizer Rosen",
        "20": "Sommerferien",
        "13": "Mediterrane Kr\u00e4uter",
        "14": "Muttertag",
        "15": "Peperoncini",
        "16": "Vernissage 16.10.09",
        "17": "Herbstkranz",
        "18": "Frohe Weihnachten",
        "19": "En guete Rutsch",
        "21": "Ligurischer Wein und \u00d6l",
        "22": "Sommerblumen",
        "23": "Sommerpause",
        "26": "Aschwanden_Vasen",
        "25": "Sommer-Fr\u00fcchte",
        "27": "neues Gesch\u00e4ft hg",
        "28": "Mimosen",
        "29": "Rosen",
        "30": "Pfingstrosen",
        "31": "Vasen Rahel",
        "32": "Schnittgr\u00fcn mit Fr\u00fcchten",
        "33": "Adventsausstellung hg 2012",
        "34": "Gef\u00e4rbtes Schnittgr\u00fcn",
        "43": "Wicken",
        "35": "Franz\u00f6sische Tulpen",
        "36": "Nelken",
        "37": "Ranunkeln, Anemonen",
        "38": "Henry Dean",
        "39": "Oliven\u00f6l",
        "40": "offen im Sommer",
        "41": "Hortensien",
        "42": "Akranz",
        "44": "Henry Dean",
        "45": "Wasseriris",
        "46": "Geburtstagsfest",
        "47": "Sonja Duo",
        "48": "Murano",
        "49": "Tulpen",
        "50": "Schwarz Sonja",
        "51": "Obovatus",
        "52": "Scabiose Stellata",
        "53": "Statitzen",
        "54": "2016",
        "55": "Caravella",
        "56": "Besnik",
        "57": "Wein und \u00d6l",
        "58": "Scilla",
        "59": "Bouquet im Sommer",
        "60": "Sommerkr\u00e4nze",
        "61": "Bilder",
        "62": "Fr\u00fchlingskr\u00e4nze",
        "63": "Duftrosen",
        "64": "Duftrosen"
    },
    "fieldName": "finalize_bill_step_1[ps]",
    "defaultValue": "",
    "className": "form-control pz-form-widget ps pz-error has-error",
    "appRootID": "APP-ID-D89C-5B86-BE78-71A8-5C11-891D-D3DB-1783",
    "placeholder": "Bitte PS w\u00e4hlen",
    "ignoredKeySuffix": "@@@"
};