var suggestions = {
    "suggestions": {
        " ": "Bitte w\u00e4hlen...",
        "1543 ": "Alec von Graffenried",
        "2625 ": "Test Company AG   Daniel G. Baumann -- Daniel Baumann",
        "2622 ": "A1- Hotel- und Restaurant Grauholz AGVerwaltung",
        "1567 ": "Act entertainment -- Georgina Boos",
        "1455 ": "advisca gmbh",
        "2541 ": "Advoaktur Krishna M\u00fcller -- Isabella Geczi",
        "1501 ": "Advodkatur56 -- Peter B\u00e4riswyl",
        "2563 ": "Advokatur & Notariat Bern -- Hans Luginb\u00fchl",
        "1045 ": "Advokatur Krneta-Gurtner  -- Annemarie Lehmann",
        "1211 ": "Advokaturb\u00fcro -- Dino Degiorgi",
        "1450 ": "AEK Bank 1826 -- Renato Gnocchi",
        "1637 ": "AEK BANK 1826 -- Simone Sutter",
        "1838 ": "Aesop -- Evelyne ",
        "604 ": "Allgemeine Orchestergesellschaft Thun",
        "2215 ": "alliance F -- Kathrin Bertschy",
        "2077 ": "Alpinofen AG -- Eliana Gisin",
        "2521 ": "ALS Verein -- Walter Brunner",
        "1497 ": "Amt f\u00fcr Landwirtschaft und NaturAmtssekretartiat",
        "1566 ": "Amt f\u00fcr Sozialversicherungen",
        "1509 ": "AON Hewitt",
        "703 ": "Apotheke Kirchenfeld -- Nicola Lutz",
        "1480 ": "Arte Cucina Manz-Ritz AG -- Florina Manz",
        "174 ": "Artengarten -- Marc Rohrbach",
        "1942 ": "Association Suisse de golf  -- Manrau Corinne",
        "2434 ": "Atelier 5 -- Claudia Eugster",
        "2406 ": "atelier a&b agArchitekten SIA -- Michael Stoller",
        "2225 ": "Atelier f\u00fcr Siebdruck -- Lorenz B\u00f6gli",
        "732 ": "Augenarzt Altstadt AGFabienne Troendle",
        "1559 ": "aurora Bestatttungen -- Jan Herri",
        "156 ": "Auto AG -- Hans Kirchen",
        "1130 ": "AvenirSocial",
        "2534 ": "AvenirSocialGesch\u00e4ftstelle Schweiz -- Kathinka Gysin",
        "1110 ": "awr AG -- Raphael H\u00e4ring",
        "821 ": "B&P Rechtsanw\u00e4lte -- Hermann Bechtold",
        "2528 ": "Baby-Rose Genossenschaft -- Werner Felber",
        "1156 ": "bagatt -- Sandra Suetterlin",
        "1958 ": "BAK Bundesamt f\u00fcr Kultur -- Martine Chalverat",
        "91 ": "Balletshop -- Lisa Schmalz",
        "1009 ": "Banque Bonh\u00f4te & Cie SA -- J\u00fcrg Legler",
        "1256 ": "Banque Bonh\u00f4te & Cie SA -- Sophie-Armelle Rinieri",
        "868 ": "B\u00e4rtschi Optik AG",
        "2584 ": "Basler&Hofmann AG -- Christina Wermuth",
        "2349 ": "Bauart Architekten und Planer AG -- Karin Gartmann",
        "1476 ": "BEKB | BCBE Marketing Region Bern -- Alexander Bucher",
        "2550 ": "Bellorini Archidekten AG",
        "1783 ": "Benevol BernBerner GenerationenHaus -- Doris Wiedmer",
        "1448 ": "Bern EXPO AG",
        "754 ": "BERNCity -- Silvia V\u00f6lgyi",
        "2342 ": "Berner Augenklinik",
        "2130 ": "Berner Fachhochschule",
        "1887 ": "Berner Fachhochschule anita.jutzi@bfh.ch -- Anita Jutzi",
        "1879 ": "Berner Fachhochschule beda.viviani@bfh.ch -- Beda Viviani",
        "1977 ": "Berner Fachhochschule heike.kaltenreider@bfh.chZentraler Rechnungseingang -- Heike Kaltenrieder",
        "1951 ": "Berner Fachhochschule karin.hauswirth@bfh.chZentraler Rechnungseingang",
        "2251 ": "Berner Fachhochschule stefanie.diviani@bfh.ch -- Stefanie Diviani",
        "1112 ": "Berner Fachhochschule Direktionpriska.iseli@bfh.chZentraler Rechnungseingang -- Priska Iseli",
        "1249 ": "Berner Fachhochschule Gesundheit -- Annemarie Dick",
        "910 ": "Berner Fachhochschule Gesundheit  Geburtshilfe -- Christina Steiner",
        "1601 ": "Berner Fachhochschule Gesundheit ruth.burla@bfh.chZentraler Rechnungseingang",
        "437 ": "Berner Fachhochschule GesundheitEmpfang",
        "1785 ": "Berner Fachhochschule GesundheitStudiengang Ern\u00e4hrung und Di\u00e4thethik -- Heidi Nussbaumer",
        "1201 ": "Berner Fachhochschule Institut Alterpamela.fecke@bfh.chZentraler Rechnungseingang",
        "1821 ": "Berner Fachhochschuledora.duener@bfh.chZentraler Rechnungseingang -- Dora D\u00fcrner",
        "2415 ": "Berner Kantonalbank AG -- Beatrice Groux",
        "801 ": "Berner Reha Zentrum -- Corinne Morandi M\u00fcller",
        "620 ": "Berner Symphonieorchester -- Renate Heer",
        "1718 ": "berufsbildnerverband bauplaner espace mittelland bernc\/o hsp-Hodler, Santschi & Partner AG",
        "1862 ": "Berufsverband f\u00fcr Coaching, Supervision und Organisationsberatung bso",
        "1138 ": "BFF Bern",
        "1647 ": "BFF Bern",
        "741 ": "BFF Bern, Direktionssekretariat  -- Veronika Breil-Z\u00fcnd",
        "991 ": "BFH Direktion WGAS -- Alexandra M\u00fcller",
        "2482 ": "Bieri&Breiter Anw\u00e4lte -- Pascale Holliger-Bieri",
        "41 ": "bigbelly GmbH -- Estelle Heiniger",
        "931 ": "Bijoux Stadelmann -- Antonio Gallo",
        "369 ": "Bilboquet -- Martine Adank",
        "2552 ": "BildungslandschaftenJacobs Fondation -- Julia Wyss Stv. Projekt Manager",
        "900 ": "Bindella terra vite vita SA -- Maria Petrarolo",
        "1926 ": "BKW Energie AGKreditorenrechnung, KS-COM -- Myriel Nussbaum",
        "1084 ": "Blausee AG",
        "1225 ": "bleufelin -- Rolf Stauffenegger",
        "2060 ": "Blinden- und Behindertenzentrum Bern",
        "1780 ": "Blinden- und Behindertenzentrum Bern -- Franziska Maurer",
        "671 ": "Blueme Ginkgo -- Claudia Holzer",
        "1695 ": "Botschaft des F\u00fcrstentums Liechtenstein -- Doris Frick",
        "1796 ": "Boutique Charivari",
        "851 ": "Boutique Indigo -- Domenica Affrutni",
        "105 ": "boutique Nelly",
        "2417 ": "Bovisi AG",
        "1517 ": "BR Bauhandel AG",
        "2581 ": "Bratschi AG",
        "1143 ": "Bread \u00e0 porter -- Patrik Bohnenblust",
        "1502 ": "Brot f\u00fcr alle -- Sibylle Spengler Inderm\u00fchle",
        "669 ": "Brunngass-Rathausgass-Leist -- Sandra Franz",
        "2479 ": "bso",
        "759 ": "BSPV, Staatspersonalverband Bern -- Matthias Burkhalter",
        "2496 ": "Bucherer AG Bern  -- Silvie Baumgartner",
        "1027 ": "Buchhandlung zum Zytglogge -- Gabriella Bader",
        "2094 ": "Bund FEG -- Mark Bertschi",
        "1858 ": "Bundesamt f\u00fcr BSV Sozial Versicherungen",
        "2076 ": "Bundesamt f\u00fcr Landwirtschaft c\/o DLZ FI EFD -- Carla Kaufmann",
        "1013 ": "Bundesamt f\u00fcr Sozialleistung",
        "2322 ": "BundesverwaltungsgerichtPr\u00e4sident -- Jean-Luc Baechler",
        "1312 ": "Bureau Gossweiler  Consultations Art & Finance",
        "1169 ": "Burgerbibliothek Bern -- Annelies H\u00fcssy",
        "1685 ": "Burgergemeinde Bern -- Lea P\u00e9riat",
        "2028 ": "Burgergemeinde Bern  Burgerkanzlei -- Brigit Steinfels",
        "2189 ": "Burgergemeinde Bern Pr\u00e4sidium -- Stefanie Gerber Fr\u00f6sch",
        "1157 ": "BurgergemeindeKanzlei & Burgerkommission",
        "2465 ": "B\u00fcrgerspital SolothurnChefsekretariat Chirurgie -- Regina Ulrich",
        "2098 ": "B\u00fcro B Architekten AG -- Cornelia Lehmann",
        "1630 ": "B\u00fcrogemeinschaft IGKG Schweiz",
        "77 ": "c.anliker -- Christoph Anliker",
        "2476 ": "Cado -- Caroline Lelli",
        "704 ": "Caf\u00e9 Xenia",
        "814 ": "Caf\u00e9-Bar Diagonal -- Caroline Jacobi",
        "2044 ": "Campanile und Michetti  Architekten AG",
        "2007 ": "Caritas Schweiz -- Daniela Krienb\u00fchl",
        "2377 ": "CASINO BERN",
        "719 ": "Casino Restaurants Bern AG -- Nilg\u00fcn B. Burkhalter",
        "1778 ": "CCB Inter -- Pierre Tavernini",
        "1553 ": "Centerclinic f\u00fcr Plastische Chirurgie",
        "1529 ": "CentrodentZentrum f\u00fcr Zahnmedizin",
        "2085 ": "Changemaker AG -- Daniela Gossweiler",
        "862 ": "Charles V\u00f6gele Mode AG -- Doris Hostettler",
        "128 ": "Chaussure Wildi -- Renate Gyger",
        "1313 ": "Chiropraktik Hirschengraben ",
        "2305 ": "Chocolatemanufacture -- Market Maly",
        "1947 ": "Chun Hee GmbH -- Eve Angst",
        "2585 ": "Ciolina Ag",
        "2510 ": "Cipio Weinbar",
        "2232 ": "City Apotheke AG Biel -- Fausta Benini",
        "1875 ": "coiff your success -- Pino Zinna",
        "1254 ": "Coiffeur 7",
        "651 ": "Coiffeur Elisa -- Elisa ",
        "2500 ": "Coiffeur Merz GmbH",
        "1159 ": "Comme il faut -- J\u00fcrg Knecht",
        "712 ": "Companys",
        "1709 ": "Compum@x EDV-Technik -- Rainer Schwarz",
        "1985 ": "Confiserie Eichenberger -- Daniel Eichenberger",
        "2104 ": "Contexte GmbH",
        "282 ": "Cosmadialog -- Suzanne Morandi",
        "2410 ": "CPH -- Mette Jensen",
        "1938 ": "CSS Versicherung ",
        "1073 ": "CTM Treuhand AG -- Urs Seiler",
        "551 ": "Cucina Iljos -- Antoniette Werndli",
        "2553 ": "CVP Generalsekretariat -- Stefan Z\u00fcger",
        "1552 ": "Dampfzentrale Bern -- Miriam Stucki",
        "1081 ": "Department Sprach- und Lit.-Wissenschaften -- Quassdorf Lic. Phil. Sixta",
        "2247 ": "Der Burgerspitel -- Susanne L\u00e4derach",
        "2158 ": "DEZA Globalprogramm Migration und Entwicklung -- Ahmed Didane",
        "820 ": "Diabetologie- und Endokrinologiezentrum -- Bruno M\u00fcller",
        "1436 ": "Die Mobiliar",
        "1924 ": "Die Mobiliar",
        "1036 ": "Die Mobiliar -- Antonella Maria Dimo",
        "1747 ": "Die Mobiliar -- Christian Grundt",
        "1270 ": "Die Mobiliar  -- Cossi Aldo",
        "2571 ": "Die Mobiliar  -- Dorothee Fuchs",
        "1236 ": "Die Mobiliar  -- Janine Guntern",
        "1161 ": "Die Mobiliar -- Laila Liechti",
        "2339 ": "Die Mobiliar -- Lorina K\u00fchni",
        "1445 ": "Die Mobiliar -- Markus Wolf",
        "2576 ": "Die Mobiliar  -- Marl\u00e8ne Schumacher",
        "2239 ": "Die Mobiliar -- Susanne Saxer  HR Managerin",
        "2517 ": "Die Mobiliar  -- Ulrich Hadorn",
        "2561 ": "Die Mobiliar  Direktion Bern  -- Daniela Lehner",
        "2065 ": "Die Mobiliar  Immobilien -- Dominik B\u00f6gli",
        "2119 ": "Die Mobiliar  Immobilien -- Sibylle Muster",
        "1995 ": "Die Mobiliar Versicherungsgesellschaft AGBenjamin.echaud@mobi.ch -- Benjamin Echaud",
        "2262 ": "die Mobiliar, Direktion Bern -- Antonella Maria Dimo",
        "1716 ": "Die MobiliarAsset Management AG",
        "1532 ": "Die MobiliarBerufliche Vorsorge -- Michael Kr\u00e4henb\u00fchl",
        "2195 ": "Die Mobliar -- Susanne Saxer",
        "532 ": "Die Schweizerische Post PostFinance -- Alexander Steinegger",
        "569 ": "Die Schweizerische Post PostFinance -- Benjamin Ingold",
        "566 ": "Die Schweizerische Post PostFinance -- Bettina Frossard-Stolz",
        "531 ": "Die Schweizerische Post PostFinance -- Christin Caldera",
        "561 ": "Die Schweizerische Post PostFinance -- Claudia Daniela Burkhard",
        "577 ": "Die Schweizerische Post PostFinance -- Corinne Treier",
        "564 ": "Die Schweizerische Post PostFinance -- Cosimo Christian Fiordiriso",
        "530 ": "Die Schweizerische Post PostFinance -- Fabian Kollros",
        "576 ": "Die Schweizerische Post PostFinance -- Franco Sorbello",
        "557 ": "Die Schweizerische Post PostFinance -- Georg B\u00f6hlen",
        "567 ": "Die Schweizerische Post PostFinance -- Ina No\u00ebmi G\u00fcbeli",
        "578 ": "Die Schweizerische Post PostFinance -- Kurt von Rohr",
        "571 ": "Die Schweizerische Post PostFinance -- Lucia Locher",
        "574 ": "Die Schweizerische Post PostFinance -- Manuela Olivieri",
        "572 ": "Die Schweizerische Post PostFinance -- Marina Malbasic",
        "559 ": "Die Schweizerische Post PostFinance -- Meinrad Brem",
        "556 ": "Die Schweizerische Post PostFinance -- Melanie Bender",
        "563 ": "Die Schweizerische Post PostFinance -- Melina Dahinden",
        "580 ": "Die Schweizerische Post PostFinance -- Philippe JeanRichard",
        "575 ": "Die Schweizerische Post PostFinance -- Reto Schmid",
        "562 ": "Die Schweizerische Post PostFinance -- Roberto Caruso",
        "570 ": "Die Schweizerische Post PostFinance -- Roland Lamprecht",
        "568 ": "Die Schweizerische Post PostFinance -- Rolf Imboden",
        "555 ": "Die Schweizerische Post PostFinance -- Roman Baumann",
        "558 ": "Die Schweizerische Post PostFinance -- Ruth Bornatico",
        "560 ": "Die Schweizerische Post PostFinance -- Silvia Burger",
        "565 ": "Die Schweizerische Post PostFinance -- Susanne Fritschi",
        "579 ": "Die Schweizerische Post PostFinance -- Sybille Walser",
        "716 ": "Die Schweizerische Post PostFinance -- Thomas Meuli",
        "573 ": "Die Schweizerische Post PostFinance -- Ursula Meyer",
        "817 ": "Die Schweizerische Post PostFinanceBeratung und Verkauf PK -- Remo Scheuner",
        "2419 ": "diff. Kommunkations AG -- Katharina Horber",
        "1513 ": "Dillon GmbH -- Patric Dillon",
        "1117 ": "Direktion f\u00fcr Finanzen, Personalund Informatik -- A. Kn\u00fcsel",
        "2462 ": "Domenig PartnerRechtsanw\u00e4lte AG -- Claudia Steffen",
        "1703 ": "Domicil Bern AG -- P. Hostettler",
        "2256 ": "Dpt of Chemistry and Biochemistry  Universit\u00e4t Bern -- Peter PD.Dr. Broekmann",
        "1855 ": "Dr. med. dent -- Nelsy Basler",
        "1797 ": "Dr. med. dent. Ch. Spycher",
        "2530 ": "Dr. med. Peter Meyer Eisenzetrum",
        "2464 ": "Dr. Schnyder GmbHMurifeldapotheke",
        "2111 ": "Dreifaktigkeitskirche -- F Wernz",
        "42 ": "DS Schmuckkultur -- Rosmarie Baumann",
        "1460 ": "Ecoplan AG -- Sandra D\u00e4nzer",
        "1232 ": "Ecoplan AG -- Stefan Suter",
        "642 ": "EDA Zentraller RechnungseingangHR Beratung DEZA Ref. Nr. 1005-70-270 -- Martina W\u00fcthrich",
        "2126 ": "Effinger Kaffeebar -- Salome Hostettler",
        "2564 ": "Eggert+Friends LLC -- Patrick Eggert",
        "1775 ": "Eglise francaise r\u00e9form\u00e9e -- Marie-Claude Slongo",
        "2554 ": "ehb",
        "2101 ": "EHB -- Isabelle Antenen",
        "2540 ": "EHB -- Ursula Schweizer",
        "1897 ": "EHB IFFP IUFFP Eidgen\u00f6ssisches Hochschulinstitut f\u00fcr Berufsbildung -- Cornilia Oertle",
        "1909 ": "EHB IFFP IUFFP Eidgen\u00f6ssisches Hochschulinstitut f\u00fcr Berufsbildung -- Beatrice Linder",
        "1918 ": "EHB IFFP IUFFP Eidgen\u00f6ssisches Hochschulinstitut f\u00fcr Berufsbildung -- Marlene Huber",
        "866 ": "Eidg. Departement f\u00fcr Verteidigung, NDB -- Eveline Wallen",
        "1257 ": "Eidg. Finanzverwaltung (EFV)DienstleistungszentrumFinanzen EFD \"Bundesrat\"REF 1001-30000",
        "2325 ": "Eidg. Hochschulinstitut f\u00fcr Berufsbildung EHB Personaldienste",
        "1499 ": "Eidg. Steuerverwaltung  (ESTV)REF-1052-10000",
        "2480 ": "Eidgen\u00f6ssische Kommunikationskommission ComCom  Sekretariat  -- Jacqueline Fischer Pulver",
        "1612 ": "Eidgen\u00f6ssisches Departement f\u00fcr Wirtschaft, Bildung und Forschung WBF -- In\u00e9s Roethlisberger",
        "1451 ": "Eidgen\u00f6ssisches Departement des Innern EDI Generalsekretariat GS-EDI -- Ursula Noti-Erpen",
        "2555 ": "Eidgen\u00f6ssisches Hochschulinstitut f\u00fcr Berufsbildung -- Regina Diering",
        "2286 ": "Einstein Kaffee & Bel \u00e9tage",
        "1922 ": "Einwohnerdienste der Stadt Bern *VSED Jubil\u00e4um vom 2.\/3.5.2019*",
        "2230 ": "Elbe GmbH -- Christine Elbe",
        "905 ": "Elfenau Park -- Franziska D\u00e4ppen",
        "780 ": "ElfenauPark -- Gabriella W\u00fclser Friedrich",
        "1121 ": "Emabssay of France -- Sophie ",
        "1046 ": "Embassy of Belgum -- Reka Singh",
        "1506 ": "Embassy of Columbia",
        "1428 ": "Embassy of Israel -- Claire Huynen",
        "1486 ": "Embassy of Japan -- Nikaido Takako",
        "1580 ": "Embassy of Korea",
        "1047 ": "Embassy of Peru",
        "2303 ": "Embasy of Spain",
        "1729 ": "Embasy of Uruguay -- Esther Nakamatsu",
        "1859 ": "Emch & Berger AG Bern",
        "2163 ": "Emmaus Kinderhilfe  -- Pierre Farine",
        "2380 ": "Emoticom AG -- Franziska Sommer",
        "1937 ": "Energie Wasser Bern -- Alexandra Freudiger",
        "1487 ": "Erben Werner Maeder -- Esther R\u00e4z",
        "2330 ": "Erziehungsdirektion BernAmt f\u00fcr Kultur\/Kulturf\u00f6rderung -- Daniela Born",
        "2316 ": "Eschmann - Contactlinsen AG Augenoptik & Optometrie -- Raphael Eschmann",
        "812 ": "ETH-Rat, Personal Stab -- Simone Bl\u00e4ttler",
        "2459 ": "Euresearch -- Nadine Liechti",
        "2526 ": "evenjo ag - brand. scene. live. -- Daniel Schmutz",
        "2456 ": "evoil\u00e0 boutique -- Esther Hermann",
        "157 ": "EWBKreditorenbuchhaltung",
        "2502 ": "extra Lanschaftsarchidekten AG -- Corinne Gerber",
        "2549 ": "EYEPARCPraxis Dr. med. Imesch",
        "850 ": "Fachhochschule NordwestschweizP\u00e4dagogische Hochschule",
        "970 ": "Fachstelle (FGS) f\u00fcr die Gleichstellung von Frauen und M\u00e4nnernStaatskanzlei des Kantons Bern -- Esther Fuchs",
        "2616 ": "Falkenberg -- Falkenberg Beata",
        "1434 ": "FC Breitenrain -- Christoph Sch\u00f6bi",
        "1884 ": "FDP Die Liberalen Frauen -- Ir\u00e8ne Thalmann",
        "937 ": "FDP Kanton Bern -- Tim Jaggi",
        "1245 ": "FDP Stadt Bern",
        "1981 ": "FDP. Die LiberalenGeneralsekretariat -- Evelyn Hofer",
        "38 ": "Ferrari SA -- Monika De Simone",
        "1139 ": "Feusi -- Isabell Witschi",
        "494 ": "Finanzdirektion -- Beatrice Simon",
        "1026 ": "Finecapital AG -- Domenic Parli",
        "364 ": "Fischerst\u00fcbli -- Suresh Sureskumaran",
        "225 ": "Form + Raum -- Barbara Hofer",
        "2514 ": "Freitagsacademie -- Marianne Leupi",
        "2326 ": "Freund & Br\u00f6nnimann AG -- Hansueli Beer",
        "646 ": "Freunde des Berner Symphonieorchesters -- Regula Haefliger",
        "582 ": "Furrer und Partner",
        "228 ": "Gander Event -- Robi Gander",
        "2490 ": "Garage Baumann Appenzell",
        "2566 ": "garominsu -- Andreas Z'Brun",
        "1684 ": "Gartenbau -- Paul Minder",
        "183 ": "G\u00e4rtnerei Krebs -- Oliver Krebs",
        "662 ": "Gastro Stadt Bern und Umgebungc\/o Casino Restaurant",
        "1477 ": "Gastro Suisse  Marketing & Kommunikation -- Astrid Haider",
        "2504 ": "Gastroenterologische Praxis Balsiger, Seibold & Partner",
        "2578 ": "gecko communication ag -- Nicole Walker",
        "2575 ": "Gef\u00e4sspraxis Bern -- Andreas Z'Burn",
        "2587 ": "Gef\u00e4sspraxis. Dr. Andreas Z'Brun",
        "1259 ": "Gemeindeverwaltung Herzogenbuchsee -- Brigitte K\u00fcnsch",
        "1799 ": "Gemeinsachftspraxis. 3 Stock. -- Nathalie Quattrocchi",
        "2009 ": "Gemeinschaftspraxis 3. Stock -- Bruno Gruber",
        "1976 ": "General Secretariat GS-FDFA -- Celia Arribas",
        "1310 ": "Generali Versicherungen",
        "1431 ": "Generalsekretariat GS-WBF -- Kurt Kneub\u00fchler",
        "1605 ": "Gesellschaft zu Ober-Gerwern",
        "1203 ": "Gesellschaft zu Pfistern -- Christian Gossweiler",
        "1241 ": "Gesellschaft zum Distelzwang -- Annelise H\u00fcssy",
        "191 ": "Gesundheitspraxis -- Susanne Born",
        "2559 ": "Gesundheitszentrum -- Mathias Blaser",
        "1507 ": "Glauser + Partner",
        "897 ": "Goldschmiedeatelier -- Maria Lutz",
        "2495 ": "Golf & Country Club Blumisberg",
        "903 ": "Gourmet15box GmbH -- Susanne Schanz",
        "1742 ": "Graber Immobilien",
        "1510 ": "Grande Soci\u00e9t\u00e9 -- Emma Germano",
        "2478 ": "Grotto Ticino -- Domenico Cafiero",
        "1917 ": "GS 1 Schwiz -- Sara Pezzuto",
        "2424 ": "GS-UVEK  Personalkasse -- Helga Fontana",
        "914 ": "Gymansium K\u00f6niz-Lerbermatt -- Jan Friede",
        "2049 ": "Gymnasium Neufeld",
        "1935 ": "Gymnasium Neufeld -- Andrea Egger",
        "2278 ": "Gymnasium Neufeld -- Monika Gerber",
        "1971 ": "Gymnasium NeufeldKanzlei",
        "1831 ": "H.P. Burkhalter+Partner AG -- Philipp Eymann",
        "1278 ": "Hamilton Lodge - Zweisimmen bei Gstaad -- Jacqueline Wegink",
        "33 ": "Hamilton Lodge Belalp -- Jacqueline Wegink",
        "1542 ": "HAND-REHA -- Stefanie Widmer",
        "2137 ": "Handteam Bern AG -- Dr. Christian M\u00fcller",
        "510 ": "Hattemer GmbH -- Sandro M. Hattemer",
        "1871 ": "Haus der Akademien -- Christine Zurbuchen",
        "1872 ": "Haus der Akademien -- Lucie Stooss",
        "1746 ": "H\u00e4usermann + Partner Notare und Rechtsanw\u00e4lte",
        "39 ": "Hautnah les Dessous",
        "2269 ": "Havas AG -- Caroline Ronzani",
        "2394 ": "HeadquarterInterior design Philosophy",
        "1865 ": "Hebammenverband",
        "2198 ": "Heilp\u00e4dagogische Schule -- Helen Dossenbach",
        "1468 ": "Heimatwerk",
        "1058 ": "Helvetas Swiss Intercooperation  -- Viviane Smette",
        "2252 ": "Helvetia environnememontHolding SADirector corporate finance & development, WMC SA -- Olivier Kobel",
        "693 ": "Helvetric Trust AG -- Domenic Parli",
        "1446 ": "Herbert Frauchiger & Silvia DubachPA Adressevon Fischer Immobilien -- Roger Staub",
        "1524 ": "Herzchirurgie -- Franz Leupi",
        "2426 ": "Herzchirurgie Klinik BeauSite -- Muriel H\u00e4ni",
        "857 ": "Heugel",
        "2438 ": "H\u00f6bi Hair AG -- Helmut Schmitz",
        "1595 ": "Hochschule Luzern -- Barbara K\u00e4ch",
        "1536 ": "Hotel Kreuz Bern AG -- Roger Brukhardt",
        "1883 ": "Hotel-Restaurant Sternen -- Gabriela Pfeuti",
        "2347 ": "HSO Wirtschaftsschule Schweiz -- Bettina B\u00fchler",
        "2558 ": "HSO Wirtschaftsschule schweiz -- Bettina B\u00fchler",
        "2435 ": "HSO Wirtschaftsschule Schweiz -- Marina Huber",
        "1733 ": "Humbel AG -- Franziska Kr\u00e4nhenb\u00fchl",
        "1825 ": "hydroplant AG -- Gerhard Zemp",
        "795 ": "hydroplant AG -- M. Zurbuchen",
        "2543 ": "Insel Gruppe AGKreditorrenbuchhaltuen, WDK-000, sandra.nyffenegger@insel.ch",
        "1533 ": "Inselgruppe AG  Insel Spital -- Marlise Reichen",
        "2546 ": "Inselgruppe AGKreditorenbuchhaltungReferenz: Prof. Siebenrock, WOK-001",
        "2357 ": "Inselspital Bern Inselgruppe AGKreditorenbuchhaltung WDK-000 -- Lea Bohm",
        "2176 ": "Inselspital, Universit\u00e4tsspital Bern  Universit\u00e4tsklinik f\u00fcr Sch\u00e4del-,  Kiefer- und Gesichtschirurgie -- Caroline Dominique Z\u00fcrcher",
        "2416 ": "InselspitalLoryhausStock U1Zimmer 54 -- Nina Bischoff",
        "2600 ": "intermarlker AG -- Flavia Sch\u00fcpach",
        "2512 ": "International Piano Series -- Natalie Lafranchi",
        "1128 ": "International Relations\/NDB -- Eveline Waller",
        "1519 ": "Interni-Raumkonzept",
        "58 ": "Internorm-Fenster AG",
        "1197 ": "Intervinum AG -- Lara Francesca Cucinotta",
        "783 ": "intgenta ag ingenieure + planer  -- Beat Aeschbacher",
        "1728 ": "intosens ag",
        "129 ": "Intraform -- Susanna Franz",
        "2186 ": "isa-Team -- Adriana Pisani",
        "1773 ": "isolutions AG -- Barbara Oppliger",
        "1599 ": "ISS Facility Services AG -- Matthias Peter",
        "1435 ": "italtours ag -- Patrizia Corradi",
        "1819 ": "JES-Teaching AG -- Schaad Evelyne",
        "2132 ": "Jodlerklub Lyss -- Sonja Rytz",
        "2152 ": "Johnson Stiftung -- Myriam Vetsch",
        "2493 ": "J\u00f6rg Lienert AG Selektion von Fach- und F\u00fchrungskr\u00e4ften",
        "2486 ": "Julius B\u00e4r -- Fabienne M\u00fcller",
        "527 ": "Kantonale Denkmalpflege",
        "2327 ": "Kantonale Denkmalpflege -- Christina Mooser",
        "595 ": "Kantonale Denkmalpflege -- Regina Fedele Gerber",
        "1040 ": "Karlen-Consulting -- Anita Karlen",
        "1472 ": "K\u00e4serei Restaurant & Bar  -- Marco Plaen",
        "1898 ": "Keel Treuhand AG",
        "1781 ": "Kellerhals Anw\u00e4lte -- Vanessa Luginb\u00fchl",
        "2463 ": "Kellerhals Carrard KIG Z\u00fcrich -- Ines P\u00f6schel",
        "70 ": "Keramikraum -- Maurizio Ferrari",
        "667 ": "Kesslergass-Gesellschaft -- Tobias Burkhalter",
        "1642 ": "KIBAG Management AG",
        "1141 ": "Kindergarten Kleefeld 1  -- Magdalena Stalder",
        "1212 ": "Kindertagesst\u00e4tte Spitalacker -- Andrea Zengaffinen",
        "2315 ": "Kindsverlust.ch -- Monika Wymann",
        "2365 ": "Kino Rex -- Jeanette-Susanne Wolf",
        "1162 ": "Kirchgemeinde Bolligen -- Beatrice Pfenninger",
        "1262 ": "Kirchgemeinde Hilterfingen -- Elisabeth St\u00e4hli-Hebeisen",
        "2458 ": "Kiriat Yearim -- Annemarie Eskenazi",
        "2165 ": "Kita Lily und Lars -- Gehrer Corinne",
        "2062 ": "Kita Matahari -- Darina H\u00fcrlimann",
        "1105 ": "Kiwnais -- John G\u00fcnther",
        "2288 ": "klingende Sammlung Zentrum f\u00fcr historische Musikinstrumente -- Barbara Glauser",
        "1604 ": "Klinik Beau-SiteAnestesie -- Daniel Sch\u00f6lly",
        "2206 ": "Klinik f\u00fcr Herz- und Gef\u00e4sschirurgie",
        "1702 ": "Koch Optik AG 646",
        "1545 ": "K\u00f6hler, St\u00fcdeli & Partner GmbH -- K\u00f6hler Barbara",
        "894 ": "Kompetenzzentrum f\u00fcr Menschenrechte -- Annegrete Nilsen",
        "2532 ": "Kompetenzzentrum Integration Thun-Oberland -- Erika B\u00e4rtschi",
        "2368 ": "konzepta.ch -- Walter Brunner",
        "1745 ": "Konzert Theater Bern -- Franziska Amb\u00fchl",
        "2271 ": "Konzertdramaturgie & k\u00fcnstlerisches Betriebsb\u00fcro (Berner Symphonieorchester) -- Barbara Honegger",
        "2484 ": "Konzerttheater Bern  Gastronomie  -- Stefan Zingg",
        "372 ": "KonzertTheaterBern -- C. Z\u00fcrcher",
        "1190 ": "KonzetTheaterBern -- Claudia Brunner",
        "1442 ": "Kosmetik Eclipse -- Corinne Kaiser",
        "1439 ": "Krebs Immobilien -- Philipp Krebs",
        "1202 ": "Krebsliga Schweiz -- Flurina Zahnd",
        "1221 ": "Krompholz -- Alexander Steinegger",
        "1984 ": "Kultur Casino Bern -- Gabriella K\u00f6nig",
        "1088 ": "Kultur Casino Bern -- Lea P\u00e9riat",
        "2518 ": "Kultur Stadt Bern  -- Annina Zimmermann",
        "2472 ": "Kultur Stadt Bern -- Miryam Melgar",
        "2579 ": "Kustmuseum Bern -- Pascale Keller",
        "828 ": "La Cucina -- Julia V\u00f6geli",
        "658 ": "Leader\u2019s Solutions AG -- Anna Katharina Laederach",
        "1579 ": "Lehrerzimmer -- Sophie Markwalder",
        "1608 ": "les passions de l`ame -- Carmen D\u00e4schner",
        "2071 ": "Lesebar  -- Cecilia Schmidt",
        "553 ": "LHASA  -- Tend\u00f6l Nemseling",
        "2173 ": "Lichtbau GmbH -- Ruedi Steiner",
        "2594 ": "Life Fitness Europe GmbH -- Sebastiano De Paola",
        "2460 ": "Lindenhofgruppe -- Sabine Z\u00fcrcher",
        "2611 ": "Lindenhofgruppe AG Buchhaltung  LTT 108 310  -- Christa Haller",
        "1627 ": "Lindenhofspital -- Christine Althaus",
        "2565 ": "Lirum Larum AG -- J\u00fcrg Affolter",
        "2407 ": "Living-Beauty AG -- Franziska K\u00e4hlin",
        "2244 ": "LOG Produktions AG -- Gianluca Tolino",
        "161 ": "Maison Diwa -- Ursula Diwa",
        "1749 ": "Maler und Gipser, herzhaft gestrichen -- Enis Spahiu",
        "2024 ": "Marta Cafe Bar -- Adrian Marthaler",
        "1193 ": "Marti Generalunternehmung AG -- Doris Kipfer",
        "2016 ": "Martin M\u00fcllerF\u00fcrsprecher und Notar -- Brigitte Hausmann",
        "2312 ": "Martina Arioli LAW -- Martina Arioli",
        "2539 ": "Martinzentrum",
        "584 ": "Marzilibr\u00fccke -- Mike Hersberger",
        "1031 ": "Mc Donald`s Management & Services -- Elisabeth de Wurstenberger",
        "2301 ": "Med. Massage Bern GmbH -- Mich\u00e9le Trepp-H\u00e4berli",
        "2485 ": "Mediaschneider AG -- Helena Maly",
        "2121 ": "Medical systems solution -- Edgar Sommer",
        "1667 ": "Medusa hair -- Salom\u00e9 Thurnheer",
        "591 ": "Meisterzyklus -- Bettina Borsani",
        "844 ": "Mekong",
        "787 ": "Midnight Projekte Schweiz",
        "1095 ": "Migros Bank AG I Region Mittelland  -- Laura De Carlo",
        "1573 ": "Migros-Genossenschafts-BundAbteilung Kreditoren LP 4\/2",
        "2621 ": "mmberatung ag -- Sabine Sch\u00fctz",
        "1187 ": "Mobi24 -- Dominique Emery Frel\u00e9choz",
        "1683 ": "Mobi24 Call-Service-Center AGReferenz:roger.fankhauser@mobi.ch",
        "2243 ": "Mobiliar 24call service centermonika.sautter@mobi.ch -- Monika Sautter",
        "2599 ": "Mobiliar Versicherungsgesellschaft AG PEKO -- Rachel Schiliro",
        "2422 ": "Modelhair life.style.art -- Helmut Schmitz",
        "1248 ": "Modernikon GmbH -- Dominik Buess",
        "1065 ": "Mojo AG -- Bj\u00f6rn Berg",
        "1057 ": "Monbijou Bern",
        "1030 ": "Monbijou Bern -- Beatrix Riesen Patzen",
        "2409 ": "Monbijou Bern  Personal  -- Luis Palma",
        "1223 ": "Movendo - Das Bildungsinstitut der Gewerkschaften",
        "1238 ": "Mr. Pickwick",
        "2095 ": "Murifeldapotheke -- Angela Schnyder",
        "2522 ": "Mus\u00e9e d'Art et d'Histoire -- Verena Villiger Steinauer",
        "2525 ": "museen bern -- Silvia M\u00fcller",
        "2488 ": "Museum Aargau -- Eva Gr\u00e4del",
        "2452 ": "Musikfestival Bern -- Elke Lohmann",
        "1564 ": "My Style",
        "2221 ": "Namaste India",
        "2429 ": "Napolitanohair -- Mara Napoletano",
        "517 ": "Nationalbank -- Margrit Hearn",
        "1687 ": "Naturhistorisches Museum -- Hanspeter K\u00e4slin",
        "1218 ": "Naturhistorisches Museum Bern -- Esther B\u00f6gli",
        "1437 ": "Navyboot Schauplatzgasse",
        "322 ": "Navyboot Switzerland AGFiliale Divarese Bern",
        "590 ": "Navyboot Switzerland AGFiliale im Globus Bern",
        "499 ": "Navyboot Switzerland AGFiliale im Wankdorf Bern",
        "615 ": "Navyboot Switzerland AGFiliale im Westside Bern",
        "498 ": "Navyboot Switzerland AGFiliale Kramgasse Bern",
        "593 ": "Navyboot Switzerland AGFiliale Marktgasse Bern",
        "2369 ": "Neue Helvetische GesellschaftTreffpunkt Schweiz -- Alec von Graffenried",
        "2431 ": "Niederer Kraft Frey Ag -- Carine Bonomi",
        "2058 ": "Nierenzentrum Bern -- Patricia Hirt",
        "2615 ": "Noord Agentur -- Nicole Trasatti",
        "1015 ": "Notariatsb\u00fcro Blumer -- Karl Blumer",
        "796 ": "Nydegger Consulting -- Peter Nydegger",
        "2275 ": "oda Gesundheit BernLeiterin Berufsmarketing\/Events -- Claudia Gehriger",
        "1243 ": "Oliva nera",
        "2453 ": "Onlinekommunikation",
        "1124 ": "Optik am Hirschengraben -- Corinne Andrea Hoffmann",
        "2414 ": "Orthoplus -- Julia Henning",
        "2620 ": "OsteoIntegral  -- Beno Friedli",
        "1233 ": "p.i.n.k. elefant gmbh -- Cordelia Hagi",
        "2598 ": "Palliative zh & sh -- Monika Obrist",
        "1814 ": "PAMB -- Eveline Pfeffer",
        "2359 ": "papilio AG- fit for future -- Maria Kellersberger",
        "2356 ": "Parkleitsystem Bern AGc\/o Haussener und Partner Notare -- Margrit Kohli",
        "867 ": "Parlament Bar & Restaurant -- Hasim S\u00f6nmez",
        "1518 ": "Partylite Trading SA -- Aranka Schlede",
        "2183 ": "Pensionskasse des Bundes Publica, Abteilung Immobilien -- Christoph Gerber",
        "2362 ": "Pepes Coiffeur  -- Peppe Turnaturi",
        "1827 ": "Personalamt der Stadt Bern",
        "2057 ": "Pfandbriefbank -- Karin Gugger",
        "653 ": "PH Bern Institut f\u00fcr Bildungsmedien -- Claudia Zulian",
        "460 ": "PHB Institut f\u00fcr Weiterbildung -- Gabrielle Schorno",
        "1757 ": "PHBern Zentrale Verwaltung Kreditorenbuchhaltungurs.gfeller@phbern",
        "2291 ": "Physioteam Naderi -- Shahrzad Naderi",
        "1075 ": "Physiotherapie, FOI, Coaching -- Franco Polesana",
        "1100 ": "Piazza Bar -- Joelle Von Arx",
        "102 ": "PIMAN Thai",
        "2400 ": "Podologie  -- Kurt B\u00fcrki",
        "1146 ": "Postauto AG -- Isabelle Jampen",
        "2605 ": "Praxis an der Uni  -- Therese Bachmann",
        "1843 ": "Praxis Anna Elmiger -- Anna Elmiger",
        "429 ": "Praxis Dr. A. Z`Brun",
        "2069 ": "Praxis Dr. Abb\u00fchl -- Marie Fleur Abb\u00fchl",
        "1641 ": "Praxis Dr. Aklin",
        "1908 ": "Praxis Dr. Beat Bigler",
        "1823 ": "Praxis Dr. Beatrice Maerki",
        "432 ": "Praxis Dr. Brunner",
        "1175 ": "Praxis Dr. Ch. Gerber",
        "519 ": "Praxis Dr. Cottier",
        "1168 ": "Praxis Dr. D. D\u00f6rholt -- Dorothe D\u00f6rholt",
        "815 ": "Praxis Dr. Durrer",
        "841 ": "Praxis Dr. Ebeling",
        "1606 ": "Praxis Dr. Fabiana Grogg",
        "1660 ": "Praxis Dr. Ferro -- Claudio Ferro",
        "443 ": "Praxis Dr. Herrenschwand",
        "782 ": "Praxis Dr. Hurni",
        "431 ": "Praxis Dr. Liechti",
        "688 ": "Praxis Dr. Liechti-Darbellay",
        "1782 ": "Praxis Dr. Lukacs",
        "1870 ": "Praxis Dr. M. B\u00fchler",
        "1961 ": "Praxis Dr. Macchi -- Marcello Macchi",
        "1481 ": "Praxis Dr. Margolin -- Mark Margolin",
        "2317 ": "Praxis Dr. med J. Henning -- Julia Henning",
        "2393 ": "Praxis Dr. med. dent -- Simone Jakob Anderegg",
        "1576 ": "Praxis Dr. med. Klemens Menzi",
        "1761 ": "Praxis Dr. med. Sylviane Gindrat -- Sylviane Gindrat",
        "1881 ": "Praxis Dr. Menzi -- Klemens Menzi",
        "2531 ": "Praxis Dr. Oliver Lehmann",
        "2174 ": "Praxis Dr. Ramseier -- Hanspeter Ramseier",
        "1142 ": "Praxis Dr. Santschi -- Annette Santschi-Friedmann",
        "435 ": "Praxis Dr. Trenkel",
        "433 ": "Praxis Dr. Untern\u00e4hrer",
        "742 ": "Praxis Dr. van den Hoek",
        "436 ": "Praxis Dr. Zoppi",
        "1016 ": "Praxis Effingerzentrum -- Peter D\u00fcrig",
        "1558 ": "Praxis f\u00fcr  Neuropsychologie -- Jacqueline Zwahlen Zosso",
        "2489 ": "Praxis im Breitenrain",
        "2574 ": "Praxis PD Dr. med. Uwe  Ebeling -- Caroline Ebeling",
        "2169 ": "Praxis Professor FernandezLindenhofspital -- Charlotte Marti",
        "2591 ": "Praxis Wallner GmbH -- Jonas Wallner",
        "698 ": "Praxisgemeinschaft -- Christoph Fry",
        "2039 ": "Privat- und Unternehmungsberatung -- Heinz Thomi",
        "1530 ": "Privatbank Von Graffenried AG -- Myriam Nepfer",
        "2395 ": "Pro Juventute Kanton Bern -- Stefan Beutter",
        "2061 ": "Pro Mente Sana -- Stefanie Stoll",
        "2487 ": "Probst Schliesstechnik AG -- Christian Probst",
        "1874 ": "Produkt FAGE -- Eva Loosli",
        "1523 ": "Prof. Dr. med. Martin MeuliChirurgische Klinik  Chiru",
        "2352 ": "Professur f\u00fcr IngenieurgeologieNO G 69.3 -- Bernadette W\u00fcrsch",
        "2148 ": "Proger Turnhalle",
        "1224 ": "proiectum Kunst bei KuhnBieri",
        "2570 ": "Proitera GmbH -- Susanne Loppacher",
        "785 ": "ProLitteris -- Isabelle Hess",
        "1587 ": "Proluma AG -- Susanna Rohner",
        "2418 ": "Public Health Services -- Laura Martinelli",
        "37 ": "Punctum Aureum -- Claudia Neuburger",
        "2580 ": "Ramseier und Stucki Architekten AG -- Renate Ruegsegger",
        "1490 ": "Rappold & Partner -- Susanne Raess",
        "668 ": "Rathaus & Brunngassleist -- Sandra Franz",
        "583 ": "Raum und M\u00f6bel -- Stefan R\u00e4z",
        "2527 ": "Raumschau -- Silvia Zwahlen",
        "718 ": "Ref. Kirche Bern-Jura-Solothurn -- Verena Garcia-K\u00f6nig",
        "1983 ": "Reformierte Kirchgemeinde BolligenSekretariat -- Silvia Gfeller",
        "475 ": "Regierungsstatthalteramt Thun",
        "1050 ": "Regioneles Schulinspektorat Bern- Mittelland",
        "1610 ": "Restaurant Arirang",
        "1625 ": "Restaurant Beaulieu -- Lucas Weder",
        "1652 ": "Restaurant Casa",
        "654 ": "Restaurant Falken-alt- -- Helene Hebeisen",
        "1901 ": "Restaurant FalkenRegattieri & Bucher GmbH -- Reto Regattieri",
        "168 ": "Restaurant Frohsinn -- Daniel Schmidt",
        "349 ": "Restaurant Harmonie AG",
        "529 ": "Restaurant Kirchenfeld -- Charlotte Rota",
        "685 ": "Restaurant Metzgerst\u00fcbli -- Andreas Gilgen",
        "1739 ": "Restaurant Mohini -- Valentin Schmid",
        "1041 ": "Restaurant Schwellenm\u00e4tteli -- Gloria Irla",
        "1515 ": "Rheumaliga Schweiz -- Katrin Bleil",
        "1936 ": "Rikscha Taxi Bern -- Sarah Meier",
        "56 ": "Ritschard U. + M. -- Matthias Ritschard",
        "930 ": "Ritz AG -- B\u00e9atrice Fuchs",
        "2588 ": "Rod Kommunikation AG -- Simone Gruber",
        "1812 ": "rohrohrohBerner \u00d6lm\u00fchle -- C\u00e9dric W\u00fcthrich",
        "2087 ": "rundum mobil GmBH -- Ursula Gertsch",
        "1789 ": "R\u00fcthy Goldschmiede GmbH -- D\u00f6hme Alexandra",
        "2229 ": "Rytz -- Arlette Schneider",
        "495 ": "Sagola Navyboot -- Mathieu R\u00fcede",
        "1033 ": "SAGW",
        "2320 ": "SAJV -- Corinne Schwegler",
        "1184 ": "Sanacare Gruppenpraxis",
        "2331 ": "Sanacare Gruppenpraxis",
        "2387 ": "sant\u00e9suisseDie Schweizer Krankenversicherer -- Sybille Baumann",
        "1358 ": "Savarys gnussw\u00e4lt -- Doris Reidy Savary",
        "1906 ": "SBB -- Andrea Zeller",
        "2557 ": "SBK Sektion Bern -- Karin Peterson",
        "2520 ": "SBV Schweizerischer Blinden-und SehbehindertenverbandGeneralsekretariat -- Sonia Pio",
        "138 ": "SCA Swiss Catering Association -- Annemarie Giger",
        "2355 ": "Schuhkult",
        "1111 ": "Schw. Zahn\u00e4rztegesellschaft -- Liliane Orlando",
        "2090 ": "Schweiz TourismusDirector Emerging Markets & Special Projects -- Federico Sommaruga",
        "1700 ": "Schweizer HausapothekePrepress Medien AG -- Sylvia Felber",
        "1701 ": "Schweizer Jugendchor -- Jean-Pierre Salamin",
        "2091 ": "Schweizer Milchproduzenten SMP -- Pamela Fl\u00fcck",
        "1135 ": "Schweizer Wanderwege",
        "2542 ": "Schweizerische Akademie  der Geistes- und Sozialwissenschaften Haus der Akademien -- Christine Kohler",
        "2253 ": "Schweizerische Akademie der Geistes- und Sozialwissenschaften -- Christine Kohler",
        "2593 ": "Schweizerische Arbeitsgemeinschaft der Jugendverb\u00e4nde",
        "1176 ": "Schweizerische Bundeskanzelic\/o Dienstleistung FI EFD",
        "1997 ": "Schweizerische Herzstiftung -- Franziska Hiltpold",
        "2224 ": "Schweizerische Mobiliar  Versicherungsgesellschaft AGsibylle.muster@mobiliar.ch -- Sibylle Muster",
        "2209 ": "Schweizerische Mobiliar deborah.hachen@mobi.ch -- Deborah Hachen",
        "2202 ": "Schweizerische Mobiliar ASSET Management AG  beatrice.grau@mobiliar.ch -- Beatrice Grau",
        "1004 ": "Schweizerische Mobiliar Direktion Berncatherine.mueller@mobi.ch",
        "1276 ": "Schweizerische Mobiliar Versicherungsgesellschaft AG Referenz: douglas.krebs@mobiliar.ch",
        "2200 ": "Schweizerische Mobiliar Versicherungsgesellschaft AG geraldine.krebs@mobiliar.ch -- G\u00e9raldine Krebs",
        "1737 ": "Schweizerische Mobiliar Versicherungsgesellschaft AG Referenz: fabio.rovelli@mobiliar.ch",
        "2592 ": "Schweizerische Mobiliar Versicherungsgesellschaft AGponnaiah.sivakumar@mobi.ch -- Sivakumar Ponnaiha",
        "1891 ": "Schweizerische Mobiliar VersicherungsgesellschaftDirektion -- Benno Meier",
        "2235 ": "Schweizerische Mobiliar VersicherungsgesellschaftDirektion Bern, daniela.lehner@mobiliar.ch -- Daniela Lehner",
        "1892 ": "Schweizerische Mobiliar Versicherungsgesellschaft AG saskia.fiel@mobiliar.ch",
        "2261 ": "Schweizerische Mobiliarcath\u00e9rine.m\u00fcller@mobliar.ch",
        "2031 ": "Schweizerische MobiliarGenossenschaft  Direktion -- Maria Degiorgi",
        "1603 ": "Schweizerische MobiliarVersicherungsgesellschaft AG -- Sandra Braunschweiler",
        "2245 ": "Schweizerische MobiliarVersicherungsgesellschaft AGbeat.odermatt@mobiliar.ch -- Beat Odermatt",
        "2461 ": "Schweizerische MobiliarVersicherungsgesellschaft AGeveline.blickensdoerfer@mobi.ch -- Eveline Blickensd\u00f6rfer",
        "2449 ": "Schweizerische MobiliarVersicherungsgesellschaft AGeveline.zimmermann@mobiliar.ch -- Eveline Zimmermann",
        "2145 ": "Schweizerische Studienstiftung  -- Sarah Beyeler",
        "1575 ": "Schweizerische UNESCO-KommissionEidg. Dep. f\u00fcr ausw\u00e4rtige Angelegenheiten EDA -- Karin Parc",
        "2260 ": "Schweizerischer Evangelischer Kirchenbund -- Beatrice Bienz",
        "2170 ": "Schweizerischer Evangelischer Kirchenbund -- Helene Meyerhans",
        "1491 ": "Schweizerischer Nationalfonds (SNF)Abteilung Kommunikation -- Martina Stofer",
        "2441 ": "Schweizerisches Bundesarchiv BAR -- Yen Tu Leonardo",
        "977 ": "Schweizerisches Rotes Kreuz -- Suzanne Aeberhard",
        "2307 ": "Schweizerisches Zentrum f\u00fcr die Mittelschule -- Marlies Eggen",
        "2589 ": "Schwizerische Mobiliar -- Gerlinde Nydegger",
        "1426 ": "SECO -- Eva Nydegger",
        "1864 ": "SECO -- Marie-Claire M\u00fcnch",
        "784 ": "Securitas SA",
        "2384 ": "Seiler&Partner -- Urs Seiler",
        "1258 ": "Sekretariat Wassmer",
        "887 ": "Sekretariat ZSB Bern -- Monika Genini",
        "608 ": "Sempervivum -- Katharina Hofer",
        "2292 ": "Senevita AG -- Daniel B\u00fcttiker",
        "2567 ": "SG Kademaro GmbH -- Roger Geuggis",
        "628 ": "Sinfonisches Blasorchester Bern -- Kathrin Keller",
        "1067 ": "Ski+Velo-Center  -- Bernhard Trachsel",
        "1692 ": "Skirts -- Jennifer Wagner",
        "2507 ": "SMAB AG Bern -- Martin Hofer",
        "877 ": "SOCIALBERNGesch\u00e4ftsstelle  -- Ueli Affolter",
        "676 ": "socialdesign -- Regula Ruflin",
        "1038 ": "Soliswiss -- Lara Frasconi",
        "1538 ": "SOLVAS -- Annemarie Lehmann",
        "2477 ": "Solvas  -- Katrin Kunz",
        "2143 ": "SOLVAS  -- Sibyl Matter",
        "2100 ": "Sonja Studer Grafik AG -- Sonja Studer",
        "2607 ": "Sozialdemokratische Partei der Schweiz -- Colette Siegenthaler",
        "1034 ": "SP Kanton Bern -- Sonja Walther",
        "1037 ": "SP Schweiz",
        "2160 ": "Spencer Stuart -- Claudia Bourassa",
        "1438 ": "Spitex Bern",
        "2354 ": "Spitex Schweiz -- Severine Stein",
        "548 ": "Spring M\u00f6bel AG",
        "1097 ": "SRK Bern Mittelland -- Julia Bez",
        "1089 ": "SRK Bern Mittelland -- Ursula Zulauf",
        "1544 ": "Staatskanzlei des Kantons Bern Dienst f\u00fcr Aussenbeziehungen -- Thobias Weibel",
        "1005 ": "Staatskanzlei des Kantons Thurgau -- Rolf Graf",
        "1505 ": "Stadt Bern, Direktion f\u00fcr Finanzen Personal und Informatik -- Angela Kn\u00fcsel",
        "1548 ": "Stadt BernDirektion f\u00fcr Sicherheit, Umwelt und EnergieAmt f\u00fcr Erwachsene- und Kinderschutz -- Sarah Congedo",
        "1648 ": "STAFF TRAINING -- Fabio B\u00fcschlen",
        "36 ": "Stahlblau -- Martin Blaser",
        "896 ": "St\u00e4hli Goldschmied",
        "523 ": "Stephan Probst + Partner AG -- Stephan Probst",
        "2468 ": "Stifftung Pro Juventute -- Irene Meier",
        "2337 ": "Stiftung Marie-Glatthard-Herren -- Urs Seiler",
        "2597 ": "Stiftung Pro Juventute -- Matias Dabbene",
        "2341 ": "Stiftung pro mente sana -- Stefanie Stoll",
        "589 ": "Stoffwechsel -- Alba Casanova",
        "2596 ": "SUISSEDIGITAL-Verband f\u00fcr Kommunikationsnetze -- Christine Von Arx",
        "2234 ": "SUISSEIMAGE -- Daniela Eichenberger",
        "2051 ": "Swiss Cancer Screening -- Annina Luginb\u00fchl",
        "1727 ": "swiss skils Bern 2014 -- Eveline Steinmann",
        "2218 ": "Swiss-Ortho-Core AG",
        "710 ": "swisscable -- Christine von Arx",
        "1656 ": "Swisscom AGInvoice Center, 7062050 -- Tim Alexander",
        "2144 ": "Swissom (Schweiz) AG -- Nicola Meier",
        "2228 ": "swissuniversities -- Caroline Fischer",
        "1177 ": "Tagesschule Steigerhubel",
        "1945 ": "Taipei Delegation",
        "2425 ": "Tamedia AGZentraler Rechnungseingang -- Arthur R\u00fctishauser\/KST 1760",
        "2192 ": "Tell & Partner AG  Verm\u00f6gensverwaltung -- Robert Akeret",
        "2516 ": "Teo Jakob -- Oliver Netth\u00f6vel",
        "344 ": "Teppich 1001 -- Antoinette Akbarzadeh",
        "976 ": "TERRE DES FEMMES Schweiz",
        "522 ": "Tex SA -- F\u00e9d\u00e9ric W\u00e4lti",
        "2513 ": "Theo Jakob AG -- Oliver Netth\u00f6vel",
        "514 ": "Therapeutin  -- Lilian Hefti",
        "2524 ": "Therapie und Trainingszentrum  -- Jolanda Scheuner",
        "2179 ": "Tiefbauamt Stadt Bern -- Ursula Wyss",
        "2155 ": "tilia Stiftung f\u00fcr Langzeitpflege  -- Kathrin H\u00e4berli",
        "2082 ": "tilia Stiftung f\u00fcr LangzeitpflegeGesch\u00e4fststelle -- Christine Chappuis",
        "1959 ": "Torten Couture -- Fabiola Studer",
        "2156 ": "Turnhalle Proger",
        "307 ": "UBS AG -- Monika Stucki",
        "2162 ": "UBS Switzerland AG -- Christoph Aerni",
        "2273 ": "UBS Switzerland AG -- Peter Schmid00128593",
        "1777 ": "UHT Consulting & Services AG -- Ueli Tschan",
        "43 ": "unbekannt",
        "1093 ": "Unia -- Nico Lutz",
        "2323 ": "UNIAPersonalabteilung -- H.P. Grossen",
        "1962 ": "Universit\u00e4re Psychiatrische Dienste Bern (UPD)Direktion Pflege und P\u00e4dagogik (DPP) -- Aebi Meister Verena",
        "581 ": "Universit\u00e4t Bern  Zentraler Rechnungseingang  REF 34-743",
        "2610 ": "Universit\u00e4t Bern Zentraler Rechnungseingang REF-008-10 -- Lucia Walter",
        "1588 ": "Universit\u00e4t BernZentraler RechnungseingangREF-31-885",
        "639 ": "Universit\u00e4tsbibliothek BernBibliothek M\u00fcnstergasse  -- Isabelle Kirgus",
        "2201 ": "Universit\u00e4tsbibliothek BernBibliothek M\u00fcnstergasse  -- Melissa Hofstetter",
        "775 ": "Universit\u00e4tsklinik f\u00fcr Frauenheilkunde -- Sophia Molo - Pflegedienst",
        "502 ": "Universit\u00e4tsklinik f\u00fcr Herz- und Gef\u00e4sschirurgie -- Marlise Reichen",
        "2498 ": "Universit\u00e4tsklinik f\u00fcr Herz- und Gef\u00e4sschirurgie -- Barbara Graf",
        "537 ": "Universit\u00e4tsklinik f\u00fcr Kinderchirurgie -- Ursula G\u00fcder",
        "2379 ": "Universit\u00e4tsspital Z\u00fcrich -- Rosalina Keune",
        "1012 ": "Universit\u00e4tsSpital Z\u00fcrichDirektion Finanzen -- Rita Ziegler",
        "2267 ": "Universit\u00e4tsSpital Z\u00fcrichDirektion FinanzenFinanzbuchhaltung",
        "840 ": "USIC -- Mario Marti",
        "2358 ": "v. Fischer Office AG -- Christoph Oeri",
        "2481 ": "v.FISCHER Recht AG -- Christa Grubwinkler",
        "1786 ": "Valiant Bank AGGesch\u00e4ftsleitung",
        "124 ": "Valion Consulting AG -- Manuela Sch\u00e4ren",
        "1868 ": "VBV -- Cornelia Meyer",
        "2608 ": "Venenpraxis Bern -- Maria Studer",
        "901 ": "Verdi Ristorante",
        "858 ": "Verein Berner Fasnacht -- No\u00eblle de Preux",
        "1929 ": "Verein Berner M\u00fcnster Kinder- und Jugendchor -- Beyeler Stefan",
        "810 ": "VFSJK s goldig Chr\u00f6nli -- Marguerite Stieger",
        "1669 ": "Vokalensemble Belcanto -- Renate Aeschbacher",
        "799 ": "Volz Central-Apotheke -- Regula Steinmann",
        "1923 ": "von Fischer Immobilien -- Amanda Kohler",
        "2614 ": "von Graffenried & Cie -- Andreas Feuz",
        "2491 ": "Von Graffenried AG Liegenschaften -- Sandra B\u00f6tschi",
        "2492 ": "Von Graffenried AG Liegenschaften -- Sandra B\u00f6tschi",
        "2529 ": "VSAO Bern  -- Janine Junker",
        "1207 ": "VWG Bern c\/o Die Mobiliar -- Claudia Moosmann",
        "791 ": "Walter Wettstein AG",
        "2340 ": "Weber + Br\u00f6nnimann AG Ingenieure, Planer und Landschaftsarchitekten  -- Susanna Mauerhofer",
        "51 ": "Wein & Sein -- Silvia Gl\u00f6ckler",
        "1152 ": "Weizenkorn -- Dieter Jost",
        "1589 ": "WENGER PLATTNER Rechtsanw\u00e4lte -- Vanessa Luginb\u00fchl",
        "1149 ": "Wincasa AG -- Alexandra B\u00fcrgi",
        "1129 ": "Wirtschafts- und KaderschuleKV Bern -- Andrea Hofmann",
        "2466 ": "Xundheitszentrum Sch\u00f6nenwerd -- Corina Lobsiger",
        "882 ": "Yogamarket -- Alexandra Frei",
        "762 ": "Zentrale Dienste",
        "2623 ": "Zentrum Paul Klee -- Eva Gr\u00e4del",
        "2403 ": "Zentrum SchlossmattRegion Burgdorf -- Christina Estermann",
        "1708 ": "Zetcom GmbH -- Barbara Austein-Sylla",
        "1710 ": "zetcom Prestations informatiques SA -- Fran\u00e7ois de Bagneux",
        "2544 ": "ZFV-Unternehmungen ",
        "808 ": "ZSB Bern -- Karin Gfeller Grehl",
        "1133 ": "Z\u00fcrcher Hochschule der K\u00fcnsteFachrichtung Film -- Claudia H\u00fcrlimann",
        "1616 ": "Esther Obert\u00e4ufer ",
        "1772 ": "Petronilla Tour ",
        "2494 ": "Ada Tanner ",
        "2147 ": "Adam Jurski ",
        "175 ": "Adelaide Tackenberg ",
        "899 ": "Adelheide Schnacke ",
        "725 ": "Adrian Peter ",
        "2151 ": "Adrien von Steiger ",
        "1679 ": "Agnes Surber ",
        "1723 ": "Ahsim Yilmaz Kurz ",
        "1235 ": "Aim\u00e9e Jespers-Perrin ",
        "2003 ": "Alain Pfulg ",
        "1017 ": "Alberto Meyer Nolli ",
        "94 ": "Alessandro Cirelli ",
        "473 ": "Alex Steinegger ",
        "982 ": "Alexander Wassmer ",
        "2002 ": "Alexandra Abplanalp ",
        "2084 ": "Alexandra Beyeler ",
        "2268 ": "Alexandra H\u00e4fliger ",
        "184 ": "Alexandra Otis ",
        "148 ": "Alexandra Perina-Werz ",
        "85 ": "Alfredina Huber ",
        "210 ": "Alice Ast ",
        "1183 ": "Alice Kistler ",
        "2073 ": "Aline Kocher ",
        "2115 ": "Alix H\u00e4nzi ",
        "1178 ": "Alois Aufschlaeger ",
        "609 ": "Alois Sch\u00e4rli ",
        "1674 ": "Alvar Spring ",
        "2569 ": "Alyssia Cagnoni ",
        "2043 ": "Amanda Kohler  -- von Fischer Immobilien",
        "2074 ": "Amber Dekic-Sollberger ",
        "597 ": "Amina Chaudri ",
        "476 ": "Andr\u00e9 Haeberli ",
        "2154 ": "Andrea Amrein ",
        "2167 ": "Andrea Geering ",
        "143 ": "Andrea Hochuli ",
        "1833 ": "Andrea Lanker ",
        "1770 ": "Andrea Locher ",
        "1911 ": "Andrea Reimers ",
        "1457 ": "Andrea Schweizer ",
        "2045 ": "Andreas Buder ",
        "2116 ": "Andreas L\u00fcthi ",
        "289 ": "Andreas Schwab ",
        "1992 ": "Andri Probst ",
        "147 ": "Ane Riz ",
        "1106 ": "Angela B\u00e4rlocher  -- Treuhand Swiss",
        "1631 ": "Angela Scalese ",
        "660 ": "Angela Zoratti ",
        "1644 ": "Angelika Chollet ",
        "2473 ": "Angelika Chollet ",
        "1115 ": "Anica Friedli ",
        "1741 ": "Anica Spirig ",
        "2442 ": "Anick Kuentz ",
        "1900 ": "Anina B\u00fcschlen ",
        "906 ": "Anita Benz ",
        "794 ": "Anita Huber ",
        "340 ": "Anita Sch\u00fctz ",
        "2469 ": "Anja Flury ",
        "1512 ": "Anja Liechti ",
        "763 ": "Anja Siebold ",
        "928 ": "Anna Aebi ",
        "1096 ": "Anna Boss ",
        "2254 ": "Anna Cesari ",
        "811 ": "Anna Eugster ",
        "1082 ": "Anna Iseli  -- Intraform ",
        "2562 ": "Anna Luceka ",
        "488 ": "Anna Molo ",
        "2423 ": "Anna Oberli ",
        "2171 ": "Anna Roche ",
        "648 ": "Anna St\u00e4hli ",
        "347 ": "Anna Studer ",
        "69 ": "Anna Maria B\u00fctikofer  -- Soliswiss",
        "2037 ": "Anna-Maria Sch\u00e4ffeler ",
        "2139 ": "Anne Blankart ",
        "1271 ": "Anne Gruaz ",
        "766 ": "Anne Schr\u00e4mli ",
        "355 ": "Anne Witschi ",
        "1735 ": "Anne-Claude Slongo ",
        "2064 ": "Anne-Laurence Noyer ",
        "1244 ": "Anne-Lise Jespers ",
        "2295 ": "Anne-Maria Wenger ",
        "1220 ": "Anne-Marie Klee ",
        "886 ": "Anne-Marie Pulver ",
        "749 ": "Anne-Marie Sch\u00e4fer ",
        "1181 ": "Annelies H\u00fcssy ",
        "2519 ": "Anneliese Liechti ",
        "1123 ": "Annelis Hebeisen ",
        "973 ": "Annemarie Hofer ",
        "723 ": "Annemarie Leu ",
        "1902 ": "Annemarie M\u00fcller ",
        "793 ": "Annemarie Mutti ",
        "368 ": "Annemarie Neuenschwander ",
        "987 ": "Annemarie Odermatt ",
        "1188 ": "Annemarie Sandmeier ",
        "630 ": "Annemarie Schlup ",
        "1155 ": "Annemarie Steiner ",
        "1198 ": "Annemarie Zahnd ",
        "1620 ": "Annette Berger ",
        "181 ": "Annette Boutellier ",
        "635 ": "Annette Jaquet ",
        "1624 ": "Annik Jordi ",
        "180 ": "Anouk Magara ",
        "2220 ": "Antoinette Hunziker ",
        "2010 ": "Antoinette Jaun ",
        "1495 ": "Antonella Fava ",
        "697 ": "Antonia Riva ",
        "934 ": "Antonio Bruno-Salini ",
        "1988 ": "Areti Guioulami ",
        "2134 ": "Ariane Apoteloz ",
        "599 ": "Arianne Moser Reinhard ",
        "917 ": "Arlette Lienhard ",
        "2219 ": "Arlette Schneider ",
        "508 ": "Arlette W\u00e4lti ",
        "626 ": "Armand Baeriswyl ",
        "1722 ": "Astrid Geister ",
        "1158 ": "Astrid Weidmann ",
        "1056 ": "Baltasar K\u00fcbler ",
        "446 ": "Barbara Bangeter ",
        "2475 ": "Barbara Br\u00fcgger ",
        "213 ": "Barbara B\u00fcrki ",
        "2311 ": "Barbara B\u00fctikofer ",
        "545 ": "Barbara Campiche ",
        "1504 ": "Barbara Fry ",
        "1474 ": "Barbara Gygi ",
        "1751 ": "Barbara Hotz ",
        "842 ": "Barbara K\u00e4ser-Gerber ",
        "1866 ": "Barbara K\u00fcpfer ",
        "2329 ": "Barbara Loop ",
        "2208 ": "Barbara Moor ",
        "1062 ": "Barbara Patzold ",
        "644 ": "Barbara Raaflaub ",
        "2083 ": "Barbara Raschle ",
        "2106 ": "Barbara Raschle ",
        "2113 ": "Barbara Raschle ",
        "1452 ": "Barbara Richner ",
        "1217 ": "Barbara Sch\u00e4r ",
        "1788 ": "Barbara Steiner ",
        "2185 ": "Barbara Stettler ",
        "830 ": "Barbara St\u00fcdeli ",
        "777 ": "Barbara von Roten ",
        "2210 ": "Barbara Waldmann ",
        "371 ": "Barbara Weber ",
        "363 ": "Barbara Widmer M\u00fcller ",
        "2457 ": "B\u00e4rni Adamek ",
        "2021 ": "Basil Holtz ",
        "1044 ": "Bea Mekel ",
        "1668 ": "Beat Baumann ",
        "1522 ": "Beat Friedli ",
        "52 ": "Beat Liechti ",
        "1755 ": "Beat Meinen ",
        "136 ": "Beat Schmid ",
        "2017 ": "Beata Falkenberg ",
        "329 ": "Beatrice Aebischer ",
        "1478 ": "Beatrice Gertschen ",
        "1979 ": "B\u00e9atrice Haller ",
        "634 ": "Beatrice Jenni ",
        "118 ": "Beatrice Lang ",
        "1252 ": "Beatrice Linder ",
        "496 ": "Beatrice L\u00f6hrer ",
        "1852 ": "B\u00e9atrice Maerki ",
        "72 ": "Beatrice M\u00fcller ",
        "165 ": "Beatrice Nicaise ",
        "1059 ": "B\u00e9atrice Pfenninger ",
        "825 ": "Beatrice Ruflin ",
        "2321 ": "B\u00e9atrice Wertli ",
        "1126 ": "Beatrix M\u00fclchi ",
        "2231 ": "Belinda G\u00f6llner ",
        "1857 ": "Benjamin Brechb\u00fchler ",
        "1899 ": "Bernadette Riesen Pfeuti ",
        "2360 ": "Bernard Steck ",
        "1107 ": "Bernhard Bischoff ",
        "1614 ": "Bernhard Matter ",
        "2503 ": "Bernhard Schuster ",
        "30 ": "Bertha Schenk ",
        "2300 ": "Bettina Elias ",
        "864 ": "Bettina Hehl ",
        "164 ": "Bettina von Greyerz ",
        "1822 ": "Bettina Zimmermann ",
        "224 ": "Betty Fontana ",
        "2402 ": "Bogdan Sutter ",
        "1049 ": "Brigit Krneta ",
        "929 ": "Brigitta Galatioto ",
        "151 ": "Brigitta Schmidt ",
        "1813 ": "Brigitte Burgermeister ",
        "2338 ": "Brigitte Duss ",
        "2474 ": "Brigitte Egli ",
        "1632 ": "Brigitte Kaiser ",
        "2346 ": "Brigitte L\u00e4uppi ",
        "2223 ": "Brigitte L\u00fcdi ",
        "1896 ": "Brigitte Schneider ",
        "738 ": "Brigitte Zumwald ",
        "1764 ": "Britta Reinsch ",
        "2080 ": "Bruder von Grafferied ",
        "2164 ": "Bruno M\u00fcller ",
        "935 ": "Carina Baumann ",
        "2000 ": "Carmen Supersaxo ",
        "1916 ": "Carol Geiser ",
        "2573 ": "Carola Baumgartner ",
        "513 ": "Carole Engel Steiner ",
        "586 ": "Carole Massarotti ",
        "2601 ": "Caroline Beyeler ",
        "2120 ": "Caroline Hammer ",
        "736 ": "Caroline Jacobi ",
        "707 ": "Caroline Stoller ",
        "2444 ": "Caroline von Graffenried ",
        "1930 ": "Caspar Lundsgaard ",
        "1308 ": "Catherine Bratschi ",
        "1140 ": "Catherine Voeffray ",
        "315 ": "Catherine Zgraggen ",
        "683 ": "Cathrine J\u00e4ggi ",
        "2432 ": "Cathrine Marcuard ",
        "2523 ": "Chantal Sauvin ",
        "2612 ": "Charle-Pascal Ghiringhelli ",
        "2613 ": "Charle-Pascal Ghiringhelli ",
        "2237 ": "Charlotte Fisler ",
        "1828 ": "Charlotte Gautscher ",
        "632 ": "Charlotte Gerber ",
        "1581 ": "Charlotte Marti ",
        "40 ": "Charlotte Sindair-Wander ",
        "1957 ": "Chri-Lou Wettstein ",
        "2240 ": "Christa Burren ",
        "1565 ": "Christian Eisenhut  -- Informatikdienste der Stadt Bern",
        "2392 ": "Christian Gossweiler ",
        "1771 ": "Christian Graber ",
        "104 ": "Christian Holenstein ",
        "525 ": "Christian Schr\u00e4mli ",
        "1449 ": "Christian Schwendimann ",
        "836 ": "Christiane Inderm\u00fchle ",
        "614 ": "Christiane Wasem ",
        "1072 ": "Christina Haas ",
        "2241 ": "Christina Mosimann ",
        "2619 ": "Christina Pfenniger  -- EDA\/Sektion Kurier ",
        "1186 ": "Christine Bhend ",
        "705 ": "Christine Bierbach ",
        "636 ": "Christine Bigler ",
        "1104 ": "Christine B\u00fchler ",
        "1766 ": "Christine Chappuis ",
        "1120 ": "Christine Felber ",
        "549 ": "Christine Fischer ",
        "1594 ": "Christine Gautschi Zuppiger ",
        "2366 ": "Christine Giger ",
        "62 ": "Christine Grunder ",
        "1459 ": "Christine Haenggi ",
        "2032 ": "Christine Hubacher ",
        "2015 ": "Christine Kipfer ",
        "1714 ": "Christine Leuenberger ",
        "1267 ": "Christine Uddin ",
        "2213 ": "Christine Vischer ",
        "1795 ": "Christine Webb ",
        "226 ": "Christoph Fry ",
        "2371 ": "Christoph Gerber ",
        "1946 ": "Christoph Haemmig Kim ",
        "2467 ": "Christoph K\u00e4hler ",
        "1609 ": "Christoph Kunz ",
        "1113 ": "Christoph Sch\u00f6bi ",
        "67 ": "Christoph Sommer ",
        "1750 ": "Christoph Stuber ",
        "362 ": "Chrsitiane Arnold ",
        "515 ": "Chrystian Ryser ",
        "863 ": "Claude Derron ",
        "1650 ": "Claude Monnier ",
        "1125 ": "Claudia Campiche ",
        "819 ": "Claudia Furrer ",
        "1011 ": "Claudia Guggisberg ",
        "1101 ": "Claudia Hari ",
        "2127 ": "Claudia Kaufmann ",
        "1154 ": "Claudia Kohler ",
        "1754 ": "Claudia Marti ",
        "2207 ": "Claudia Merz ",
        "701 ": "Claudia Meyer ",
        "1485 ": "Claudia Schauerte ",
        "1228 ": "Claudia St\u00e4bler ",
        "2019 ": "Claudia Thoma ",
        "544 ": "Claudia Vivalda ",
        "216 ": "Claudio Clematide ",
        "179 ": "Cordelia Wyder ",
        "1931 ": "Corina Alchenberger ",
        "650 ": "Corinne Braunschweig ",
        "1860 ": "Corinne H\u00e4cki ",
        "1018 ": "Corinne Jenni ",
        "2272 ": "Corinne Lanz ",
        "706 ": "Corinne Vorburger ",
        "753 ": "Corinne Z\u00fcrcher ",
        "1851 ": "Corinne und Ruth M\u00fcller ",
        "873 ": "Corinne-Isabelle Robert ",
        "140 ": "Cornelia Br\u00fcndler ",
        "100 ": "Cornelia H\u00e4fliger ",
        "360 ": "Cornelia Oertle ",
        "1007 ": "Cornelia Stucki ",
        "2446 ": "Cornelia Zangger ",
        "909 ": "Cristina Riva ",
        "2577 ": "Daiana Leuenberger ",
        "1867 ": "Daniel Bloch ",
        "2427 ": "Daniel Graf ",
        "2430 ": "Daniel Schmid ",
        "1163 ": "Daniel Schwarz ",
        "1145 ": "Daniel Stettler  -- Glasmalerei",
        "912 ": "Daniel Widmer ",
        "855 ": "Daniel Witkowsky ",
        "1165 ": "Daniela Amb\u00fchl ",
        "358 ": "Daniela Freiburghaus ",
        "2560 ": "Daniela Lehner  -- Die Mobiliar  Direktion Bern ",
        "2096 ": "Daniela M\u00fcller ",
        "130 ": "Daniela Reimann ",
        "1281 ": "Daniela Richner-Bruhin ",
        "190 ": "Danielle Cosandey ",
        "554 ": "Dave Marshall ",
        "695 ": "David Costa ",
        "1493 ": "David Schiller ",
        "1955 ": "David Studer ",
        "1359 ": "David Vadura ",
        "1526 ": "David Wyss ",
        "927 ": "Debora Gubler ",
        "1939 ": "Debora Kaufmann ",
        "1582 ": "Denis Jeitziner ",
        "16 ": "Denise Boutellier ",
        "2067 ": "Densie Schraner ",
        "486 ": "Detlef Knaack ",
        "2102 ": "Didier Mahon ",
        "1265 ": "Dieter Borer ",
        "1698 ": "Dietmar Bignion ",
        "1682 ": "Dino Degiorgi ",
        "892 ": "Dominique B\u00fcrgi ",
        "214 ": "Dominique Chrsit ",
        "2583 ": "Dominique Fl\u00fceler ",
        "2447 ": "Dominique Schindler ",
        "2274 ": "Dorian Dutti ",
        "824 ": "Doris Ballinari ",
        "339 ": "Doris Diemant ",
        "2149 ": "Doris Frick ",
        "1246 ": "Doris Leuthard ",
        "1689 ": "Doris Reidy ",
        "807 ": "Doris Reinhard ",
        "64 ": "Doris Schneider ",
        "2193 ": "Dorothea Wildbolz ",
        "1982 ": "Doroth\u00e9e Keller ",
        "2270 ": "Dorothee Morell ",
        "2398 ": "Dory Salzmann ",
        "869 ": "Dory Seccabiani ",
        "132 ": "Edith Gertsch ",
        "755 ": "Eilsabeth Schaad ",
        "60 ": "Elisabeth Adam ",
        "1116 ": "Elisabeth B\u00e4r ",
        "739 ": "Elisabeth Dubach ",
        "2214 ": "Elisabeth Emme ",
        "1654 ": "Elisabeth Hess ",
        "2351 ": "Elisabeth Hofmann ",
        "2370 ": "Elisabeth Huber ",
        "769 ": "Elisabeth Riedi ",
        "832 ": "Elisabeth R\u00f6sli ",
        "2023 ": "Elisabeth R\u00fcegg ",
        "2298 ": "Elisabeth Siegfried ",
        "613 ": "Elisabeth Staub ",
        "2309 ": "Elisabeth Weber ",
        "1885 ": "Elisabeth Weibel ",
        "187 ": "Elisabeth Widmer ",
        "73 ": "Elisabeth Wirz ",
        "629 ": "Elisabeth Z\u00f6lch ",
        "713 ": "Ella Urben ",
        "692 ": "Elsa Werthemann ",
        "1970 ": "Elsbeth Bamert ",
        "485 ": "Elsbeth Fankhauser ",
        "2178 ": "Emely M\u00e4der ",
        "1028 ": "Emerita Rusca ",
        "1423 ": "Emilia Beugger ",
        "2177 ": "Emma Germano ",
        "26 ": "Erich Lehmann ",
        "1083 ": "Erika Bracher ",
        "2250 ": "Erika Keller ",
        "1725 ": "Erika Leuenberger ",
        "444 ": "Erika Parris ",
        "2187 ": "Erika Schiffmann ",
        "507 ": "Erika Schulthess ",
        "1237 ": "Erna Schenk ",
        "1842 ": "Esther Clavadetscher ",
        "1549 ": "Esther Hermann ",
        "351 ": "Esther Hirschi ",
        "2405 ": "Esther Perren ",
        "765 ": "Esther R\u00e4z ",
        "99 ": "Esther Steiner ",
        "1844 ": "Esther Wyser ",
        "2318 ": "Esther Zahnd ",
        "617 ": "Eva Bruestlein ",
        "1488 ": "Eva Chiappini ",
        "856 ": "Eva Dolder ",
        "221 ": "Eva Fauser ",
        "2109 ": "Eva Gr\u00e4del ",
        "166 ": "Eva Hefti ",
        "35 ": "Eva Hostettler ",
        "690 ": "Eva Loosli ",
        "1216 ": "Eva Walther ",
        "71 ": "Eva Zbinden ",
        "2108 ": "Eveline Gfeller ",
        "1817 ": "Eveline Iannelli ",
        "681 ": "Eveline Reist ",
        "1873 ": "Evelyn Hofer ",
        "2157 ": "Evelyne Defila ",
        "1846 ": "Evelyne Tanner ",
        "618 ": "Evelyne Z\u00fcrcher ",
        "1109 ": "Eyup Ko\u00e7 ",
        "2153 ": "Fabian Liechti ",
        "1119 ": "Felber Christine ",
        "1251 ": "Ferdinand Oberholzer ",
        "24 ": "Fiona Losinger ",
        "1214 ": "Fiorenza Cagnoni ",
        "2556 ": "Flavia Lauper ",
        "215 ": "Florence Clavien ",
        "1793 ": "Florina Wildeisen ",
        "1829 ": "Franca Contratto ",
        "853 ": "Franca Julio ",
        "1042 ": "Franco Polesana ",
        "2376 ": "Francoise Arbex ",
        "2093 ": "Francoise Baumgartner ",
        "1882 ": "Francoise Bourquin-Wirz ",
        "1356 ": "Franz Neff ",
        "448 ": "Fr\u00e4nzi Kr\u00e4henb\u00fchl ",
        "1272 ": "Fr\u00e4nzi Rudin ",
        "2445 ": "Franziska Amb\u00fchl ",
        "53 ": "Franziska Badertscher ",
        "1839 ": "Franziska Huber ",
        "2199 ": "Franziska Landolf ",
        "1090 ": "Fr\u00e9d\u00e9ric Rocherey ",
        "2548 ": "Frederike Bock ",
        "1768 ": "Freidrich Lersch ",
        "2041 ": "Fritz Leu ",
        "680 ": "Fulvia Robbiani ",
        "2372 ": "Furrer Sistina ",
        "2033 ": "Gabriel Zosso ",
        "1230 ": "Gabriella Fry ",
        "1934 ": "Gabrielle Bouzas ",
        "1118 ": "Gaby Vuillemin ",
        "740 ": "Genevieve Michaud ",
        "1726 ": "Georg Stein ",
        "992 ": "Georges B\u00fchlmann ",
        "891 ": "Gerhard Hirschi ",
        "1748 ": "Gerhard Zemp ",
        "1227 ": "Gerlinde Nydegger ",
        "19 ": "Gerry Cirelli ",
        "1171 ": "Gianni Rizzo ",
        "1551 ": "Gina Franz ",
        "1665 ": "Giorgio Loderer ",
        "284 ": "Giovanni Salerno ",
        "520 ": "Gisela Suter ",
        "286 ": "Giulia Schnyder ",
        "2604 ": "Grace Schild ",
        "2025 ": "Graziella Fiala ",
        "1274 ": "Greti Baumann ",
        "2190 ": "Gurli Jensen ",
        "2290 ": "Hannah Sutter ",
        "500 ": "Hannelore Castaldo ",
        "1153 ": "Hannes Teuscher ",
        "881 ": "Hans Gurtner ",
        "737 ": "Hans Horlacher ",
        "2097 ": "Hans Georg Nussbaum ",
        "1469 ": "Hans Martin Hadorn ",
        "2055 ": "Hans Uli Richard ",
        "20 ": "Hans-Martin Ott ",
        "2505 ": "Hans-Ulrich Hardmeier ",
        "1440 ": "Hanspeter Bys\u00e4th ",
        "1792 ": "Hanspeter Merz  -- BEKB",
        "890 ": "Hanspeter Ramseier ",
        "1309 ": "Hanspeter Z\u00fcrcher ",
        "1479 ": "Harald Hase ",
        "2328 ": "Hedwig Jenni ",
        "2159 ": "Hedwig Zingg Sanchez ",
        "2515 ": "Heidi Althaus ",
        "2511 ": "Heidi Fedeli  Sch\u00f6nberg ",
        "2172 ": "Heidi Fischer ",
        "2203 ": "Heidi Jaun ",
        "2285 ": "Heidi K\u00e4mpf ",
        "809 ": "Heidi K\u00f6chli ",
        "474 ": "Heidi Nydegger ",
        "28 ": "Heidi Rohrer ",
        "1424 ": "Heidi Schumacher ",
        "189 ": "Heinz Baur ",
        "979 ": "Heinz Reichardt  -- Optik am Hirschengraben",
        "1213 ": "Helen Stark ",
        "361 ": "Helene Baur ",
        "1963 ": "Helene Oester ",
        "299 ": "H\u00e9l\u00e8ne Steck ",
        "631 ": "Helene Stucki ",
        "295 ": "Helga Spors ",
        "870 ": "Herbert Karch ",
        "17 ": "Hilde Buchs ",
        "963 ": "Hili Jenny ",
        "2547 ": "Holger Schmid ",
        "1064 ": "Hugo Brugger ",
        "1003 ": "Ilse Christeller ",
        "673 ": "Ilse Eliza Brockhaus ",
        "1253 ": "Ines R\u00f6thlisberger ",
        "15 ": "Irene B\u00f6siger ",
        "694 ": "Irene Bumbacher ",
        "2146 ": "Irene Eggenschwiler ",
        "2506 ": "Irene Gonzalo ",
        "1200 ": "Irene Ingold ",
        "2114 ": "Irene Peier ",
        "2227 ": "Irene Peyer ",
        "1132 ": "Irene Scheidegger ",
        "743 ": "Irene Schl\u00e4ppi ",
        "1715 ": "Irene Tschanz ",
        "2013 ": "Ir\u00e9ne Wyss ",
        "1806 ": "Irina Felber ",
        "257 ": "Isabel K\u00fcenzi ",
        "159 ": "Isabel Leuenberger ",
        "1071 ": "Isabel Remund ",
        "61 ": "Isabelle Adam ",
        "103 ": "Isabelle Clemetson ",
        "2068 ": "Jacqueline B\u00fchlmann & Luca Cirigliano ",
        "335 ": "Jacqueline Ryffel ",
        "969 ": "Jacqueline Zwahlen ",
        "2401 ": "Jamila Rivas ",
        "2048 ": "Jane Spring ",
        "2248 ": "Janine Balz-Greminger ",
        "847 ": "Janine Birchler ",
        "2501 ": "Jaqueline Peter ",
        "2397 ": "Jasmin M\u00fchlemann ",
        "2107 ": "Jasmine Kleiner ",
        "1921 ": "Jasmine Wagner ",
        "2135 ": "Jassika Sattler ",
        "2197 ": "Jeanette Wolf ",
        "827 ": "Jeanne Froidevaux ",
        "1068 ": "Jeannine Ryser ",
        "1835 ": "Jenifer Wagner ",
        "2072 ": "Jennifer Herren-Eggenberger ",
        "1914 ": "Jessica Verri ",
        "1736 ": "Jessie Sommer ",
        "677 ": "Jimmy Gyger ",
        "2053 ": "Joana Brogini ",
        "2181 ": "Joel Bauer ",
        "2363 ": "Johanna Zawadynska ",
        "1166 ": "Johanne Le Priol ",
        "2375 ": "Jon Lori ",
        "1662 ": "Jonas Wallner ",
        "2533 ": "J\u00f6rg und Claudia Zumstein ",
        "2264 ": "Jos\u00e9e Schild ",
        "1659 ": "Josephine Jeaninne ",
        "1048 ": "Josette Leuenberger ",
        "137 ": "Joy Matter ",
        "1234 ": "Jris Weilemann ",
        "1928 ": "Judith Eichenberger ",
        "2390 ": "Judith Hoppe ",
        "975 ": "Judith Liniger ",
        "116 ": "Judith N\u00e4geli ",
        "1425 ": "Judith Schneider-N\u00e4geli ",
        "484 ": "Judith Stucki ",
        "1907 ": "Jule V\u00f6geli ",
        "2166 ": "Julia Frei ",
        "689 ": "Julia Guckau ",
        "1516 ": "Julia Liechti ",
        "2038 ": "Julia Ritzler ",
        "1462 ": "Julia Spetzler ",
        "254 ": "Julie Bessier ",
        "1675 ": "Julie von Mandach Greminger ",
        "516 ": "J\u00fcrg L\u00e4uchli ",
        "285 ": "J\u00fcrg Schmid ",
        "1663 ": "J\u00fcrg St\u00e4hli ",
        "1769 ": "Karin H\u00e4nni ",
        "2081 ": "Karin Kocher ",
        "2180 ": "Karin Matt ",
        "711 ": "Karin Rieder ",
        "280 ": "Karin Sauer ",
        "776 ": "Karin Schneider ",
        "2450 ": "Karin Tschanz ",
        "746 ": "Karin Wechsler ",
        "2412 ": "Karolina Biro ",
        "2455 ": "Katarina Kosanovic ",
        "2078 ": "Katharina Grogg ",
        "68 ": "Katharina Kellerhals ",
        "2012 ": "Katharina Lienhard ",
        "665 ": "Katharina M\u00fchlemann ",
        "1975 ": "Katharina M\u00fcller ",
        "1622 ": "Katharina Sch\u00e4r ",
        "1762 ": "Katharina Zimmermann ",
        "472 ": "K\u00e4thi Jaberg ",
        "1291 ": "K\u00e4thi Schneider ",
        "2008 ": "Kathrin Aeberhard ",
        "1255 ": "Kathrin Endner ",
        "1010 ": "Kathrin M\u00fchlemann ",
        "843 ": "Kathrin Wegm\u00fcller ",
        "1730 ": "Kathrin Wiedmer ",
        "2001 ": "Kathrin Z\u00f6lch ",
        "1673 ": "K\u00e4thy Boss ",
        "320 ": "Kathy Phillipps Feuz ",
        "160 ": "Katja Wunderlich ",
        "1500 ": "Katrin Batt ",
        "467 ": "Katrin Haemmig ",
        "860 ": "Katrin Wegm\u00fcller ",
        "317 ": "Katrin Zollinger ",
        "1890 ": "Kendra Stalder ",
        "848 ": "Konrad B\u00e4hler ",
        "1191 ": "Kora Schneider ",
        "1569 ": "Kurt Baumgartner ",
        "702 ": "Kurt Sch\u00fcpbach ",
        "1903 ": "Kushtrim Krasniqi ",
        "1583 ": "Ladina Schmidt ",
        "2196 ": "Landolf Franziska ",
        "2411 ": "Laura Blagho ",
        "2277 ": "Laura Bretscher ",
        "2399 ": "Laura Foglia ",
        "1932 ": "Laura Meier ",
        "2568 ": "Lauren Edwards ",
        "1475 ": "Laurence Bonsma ",
        "1080 ": "Laurence Gygi ",
        "1707 ": "Lenka Rados ",
        "1122 ": "Leonie Stein ",
        "171 ": "Lidya Felber ",
        "2319 ": "Liliane Mumenthaler ",
        "86 ": "Lilo Fankhauser ",
        "34 ": "Lilo Weibel ",
        "1969 ": "Linda H\u00f6fliger ",
        "816 ": "Linda Weibel ",
        "1571 ": "Lis Vogel ",
        "664 ": "Lisa Dick ",
        "144 ": "Lisa Feiler ",
        "1905 ": "Lisa Gasser ",
        "2040 ": "Lisa Gasser ",
        "768 ": "Lisbeth Affolter ",
        "1651 ": "Lisbeth Gildehaus ",
        "835 ": "Liselotte Wyssbrod ",
        "2142 ": "Livia Greco ",
        "1915 ": "Livia Neuweiler ",
        "733 ": "Livia Reber ",
        "1856 ": "Loredana Casablanca ",
        "1853 ": "Lorenz R\u00e4ber ",
        "1690 ": "Loris Hausammann ",
        "645 ": "Lotti Siebenh\u00fcner ",
        "18 ": "Louise B\u00fctikofer ",
        "2304 ": "Louise Casty ",
        "1960 ": "Loven Pater ",
        "2022 ": "Lucie Keller ",
        "603 ": "Luise Schmid ",
        "1136 ": "Lukas Schmutz ",
        "735 ": "Lydia Stern ",
        "2226 ": "M. Bircher ",
        "2538 ": "Madelaine Oeri ",
        "1051 ": "Madeleine Hirsiger ",
        "663 ": "Madeleine Krippendorf ",
        "998 ": "Madeleine von B\u00fcren ",
        "922 ": "Madeleine Vuillemin ",
        "721 ": "Magdalena Stalder ",
        "2042 ": "Mama Bratschi ",
        "1841 ": "Mama Lepore ",
        "1974 ": "Manfred Bohnenblust ",
        "2124 ": "Manfred Lang ",
        "1429 ": "Manuel Sch\u00e4rer ",
        "206 ": "Manuela Baumann ",
        "123 ": "Manuela Lardo ",
        "921 ": "Manuela Naef-Bianchi ",
        "607 ": "Manuela Schmundt-Wyss ",
        "480 ": "Marc Bergundtal ",
        "1167 ": "Marc Kilcher ",
        "2440 ": "Marc M\u00fcrner ",
        "2029 ": "Marc Pia ",
        "1774 ": "Marcel Bl\u00e4si ",
        "2437 ": "Marco Janner ",
        "2280 ": "Marco Rentsch ",
        "2030 ": "Marco Schibig ",
        "2595 ": "Marcus B\u00e4r ",
        "2282 ": "Margareta Arnold ",
        "1635 ": "Margareta Hehl ",
        "1638 ": "Margaretha Reber ",
        "1989 ": "Margaritha Staudenmann ",
        "1744 ": "Margot Ruprecht ",
        "2618 ": "Margrit Bircher ",
        "939 ": "Margrit Brunner ",
        "98 ": "Margrit H\u00f6nger ",
        "63 ": "Margrit Jean-Richard ",
        "1847 ": "Margrit Kessler ",
        "984 ": "Margrit L\u00fcthi ",
        "1456 ": "Margrit L\u00fcthy ",
        "2103 ": "Margrit Rampa ",
        "996 ": "Margrit Rhyn ",
        "800 ": "Margrit Siegenthaler ",
        "621 ": "Margrit Spring ",
        "708 ": "Margrith Gillmann ",
        "981 ": "Maria Boog ",
        "2606 ": "Maria Gebs ",
        "366 ": "Maria Renaud ",
        "176 ": "Maria Schmid ",
        "173 ": "Maria Luisa Politta ",
        "2266 ": "Maria-Lena Aebi ",
        "2572 ": "Marialuisa Cavelti ",
        "823 ": "Mariann K\u00fcnzi ",
        "786 ": "Marianne Berger ",
        "1980 ": "Marianne Bretscher ",
        "2551 ": "Marianne Br\u00fcgger ",
        "978 ": "Marianne Burkhalter ",
        "1547 ": "Marianne Daellenbach ",
        "726 ": "Marianne Dill ",
        "1787 ": "Marianne Huber ",
        "2211 ": "Marianne Kaelin ",
        "1292 ": "Marianne Keune ",
        "788 ": "Marianne Krenger ",
        "1160 ": "Marianne Leupi ",
        "101 ": "Marianne M\u00fcller ",
        "1713 ": "Marianne M\u00fcller-Matter ",
        "1103 ": "Marianne Nager-Cosandey ",
        "342 ": "Marianne Rappo ",
        "1053 ": "Marianne Rouge ",
        "2306 ": "Marianne Strahm ",
        "447 ": "Marianne Stress ",
        "2265 ": "Marianne Trefzer ",
        "2408 ": "Marianne Ueltschi ",
        "185 ": "Marianne Wille ",
        "587 ": "Marianne Woodtli ",
        "1850 ": "Marianne Zeman ",
        "328 ": "Marianne Zimmermann ",
        "2308 ": "Marianne & Stefan Sorgen ",
        "2184 ": "Marie-Anne Villars ",
        "1967 ": "Marie-Annick Boss ",
        "2258 ": "Marie-Fleur Abb\u00fchl ",
        "908 ": "Marie-Jos\u00e9e Kuhn ",
        "2545 ": "Marie-Louise Belz ",
        "1956 ": "Marie-Th\u00e9r\u00e8se Breganti ",
        "2191 ": "Marie-Therese Muheim ",
        "1150 ": "Marietta Kaeser ",
        "2343 ": "Marilena Mazzamuto ",
        "1758 ": "Marina Beyeler ",
        "902 ": "Mario Venzago ",
        "1944 ": "Marion Grund ",
        "923 ": "Marisa Ferretti ",
        "875 ": "Mark Sollberger ",
        "2483 ": "Markus B\u00fcrge ",
        "2034 ": "Markus H\u00e4rdi ",
        "54 ": "Markus Rohrbach ",
        "1732 ": "Markus Siegfried ",
        "23 ": "Marl\u00e8ne Laesser ",
        "2259 ": "Marlies B\u00e4cher ",
        "217 ": "Marlies De Cataldo ",
        "2246 ": "Marlies Kornfeld ",
        "2205 ": "Marlis Steffen ",
        "125 ": "Marlise Jaeggi ",
        "936 ": "Marlise Prince ",
        "781 ": "Marlise Reichen ",
        "115 ": "Martha Frank ",
        "2367 ": "Martin Erpen ",
        "1877 ": "Martin Kamber ",
        "2378 ": "Martina Keller ",
        "2138 ": "Martina Overthun ",
        "647 ": "Martina Pfister ",
        "2027 ": "Martina Strausak ",
        "1420 ": "Martine Kuhn ",
        "212 ": "Matthias Burkhalter ",
        "1432 ": "Matthias Siebmann ",
        "32 ": "Max Schmidhauser ",
        "1803 ": "Maya Ritzler ",
        "2175 ": "Melanie JeanRichard ",
        "728 ": "M\u00e9lanie Meyer Martena ",
        "119 ": "Mercedes Matas ",
        "1994 ": "Meret L\u00fcthi ",
        "2161 ": "Michael Gfeller ",
        "2617 ": "Michael Kaufmann ",
        "2070 ": "Michael Kellerhaus ",
        "2066 ": "Michael Oberli ",
        "273 ": "Michael Rath ",
        "1099 ": "Michaela Cerullo ",
        "1628 ": "Mike Dubois ",
        "1753 ": "Milde Egger ",
        "838 ": "Mil\u00e8ne L\u00fcthy ",
        "1878 ": "Mira Baldegger ",
        "2443 ": "Mira Gasser ",
        "1023 ": "Mireille Julien ",
        "1712 ": "Miriam Etter ",
        "2204 ": "Miriam Nepfer ",
        "1886 ": "Mirjam Fluri ",
        "1294 ": "Mirtha Renfer ",
        "938 ": "Mischa Peter ",
        "1556 ": "Monica Bilfinger ",
        "1686 ": "Monica Schwarz ",
        "356 ": "Monika Bangerter ",
        "757 ": "Monika Blattmann ",
        "1743 ": "Monika Graf ",
        "359 ": "Monika Haller ",
        "25 ": "Monika L\u00fcthi ",
        "2054 ": "Monika M\u00fcller ",
        "1681 ": "Monika Wenger ",
        "1489 ": "Monique Aeschbacher ",
        "1546 ": "Monique Berger ",
        "997 ": "Monique Liechti-Darbellay ",
        "1137 ": "Muriel Langenberger ",
        "1231 ": "Muriel Pf\u00e4ffli ",
        "2428 ": "Myriam Cibolini ",
        "1525 ": "Myriam Nussbaum ",
        "2056 ": "Nadine Markwalder ",
        "1247 ": "Nadja L\u00fcthi ",
        "194 ": "Nathalie M\u00fcller ",
        "1802 ": "Nathanael Regez ",
        "797 ": "Nelly G\u00fcller ",
        "1752 ": "Nelly Iliev ",
        "1091 ": "Nelly R\u00e4tz ",
        "1022 ": "Nelly Tschanz ",
        "730 ": "Nia Hakki ",
        "1205 ": "Nicole Beutler ",
        "988 ": "Nicole Eggenberger ",
        "2334 ": "Nicole Frick ",
        "146 ": "Nicole Hartmann ",
        "2086 ": "Nina Kamber ",
        "925 ": "Nina Nyffenegger ",
        "1029 ": "Nina W\u00e4geli ",
        "962 ": "No\u00eblle de Preux ",
        "2052 ": "Noelle Fischer ",
        "2110 ": "Noemi Gafner ",
        "2046 ": "Noemie Zumofen ",
        "434 ": "Norbert Sch\u00fctz ",
        "354 ": "Norma Kellenberger ",
        "1527 ": "Nuno Da Sliva ",
        "911 ": "Pamela K\u00f6nig ",
        "1697 ": "Pascal Romann ",
        "1355 ": "Pascal Schweizer ",
        "1978 ": "Pascale Bellorini ",
        "720 ": "Pascale Hasler ",
        "1791 ": "Pascale Schmid ",
        "731 ": "Patricia Hirt ",
        "1953 ": "Patricia Rugoletti ",
        "822 ": "Patricia Shams ",
        "1174 ": "Patrick Bohnenblust ",
        "1808 ": "Patrick Holtz ",
        "1275 ": "Patrick L\u00e4derach ",
        "1596 ": "Patrick Lafranchi ",
        "756 ": "Patrick Schocher ",
        "2242 ": "Patrik Wirth ",
        "2536 ": "Patrizia Lardelli ",
        "1263 ": "Patrizia Lardelli ",
        "2036 ": "Paul Burkhard ",
        "326 ": "Paul Christener ",
        "1098 ": "Peter B\u00e4rswyl ",
        "1144 ": "Peter Betts ",
        "805 ": "Peter Bohny ",
        "915 ": "Peter D\u00fcrig ",
        "2391 ": "Peter Kistler ",
        "854 ": "Peter K\u00fcnzler ",
        "1069 ": "Peter Lienhard ",
        "852 ": "Peter M\u00fcller ",
        "1854 ": "Peter Ruth ",
        "1173 ": "Peter Stoffel ",
        "1070 ": "Petra Busch ",
        "1268 ": "Pia Ammann ",
        "1863 ": "Pia B\u00fcrgler ",
        "2609 ": "Pia Campanille ",
        "1763 ": "Pia Klaus ",
        "177 ": "Pia Stucki ",
        "2212 ": "Piroska Kiss ",
        "1602 ": "Priska Hellm\u00fcller ",
        "656 ": "Priska Kunz ",
        "242 ": "Rachel Harnisch ",
        "550 ": "Rachel Schmid Pappa ",
        "1912 ": "Rahel M\u00fcller ",
        "27 ": "Rahel Reusser ",
        "2140 ": "Rahel Stuker ",
        "2386 ": "Ralph Ammann ",
        "752 ": "Rapahel Eschmann ",
        "1568 ": "Raphael M\u00fcller ",
        "2020 ": "Raquel Perez ",
        "2590 ": "Rebecca Schifferli ",
        "334 ": "Regina Hoffmann ",
        "255 ": "Regina Kraushaar ",
        "600 ": "Regula Amacher ",
        "1427 ": "Regula Bircher ",
        "833 ": "Regula Gartenmann-Keller ",
        "1811 ": "Regula Herzig ",
        "2079 ": "Regula Hess ",
        "672 ": "Regula Luginb\u00fchl ",
        "490 ": "Regula Moosbrugger  -- Historisches Lexikon der Schweiz",
        "1664 ": "Regula Schmid ",
        "1189 ": "Regula Schweizer ",
        "2310 ": "Regula Streiff ",
        "1584 ": "Regula Zi\u00f6rjen ",
        "330 ": "Reinhard Graf ",
        "2586 ": "Remo H\u00e4cki ",
        "1794 ": "Remy Linder ",
        "188 ": "Renate Schlawin ",
        "1463 ": "Renate Sch\u00fcrch, neu Brignoni ",
        "1079 ": "Renate Christina Mordasini ",
        "1810 ": "Renato Gnocchi ",
        "1570 ": "Ren\u00e9 Schneider ",
        "163 ": "Ren\u00e9 Sommer ",
        "1809 ": "Reto Jent ",
        "126 ": "Richard Carbonnelle ",
        "122 ": "Rico St\u00f6ssel ",
        "186 ": "Rita Ebeling ",
        "2324 ": "Rita Hugentobler ",
        "259 ": "Rita Kurmann ",
        "627 ": "Rita W\u00fctrich ",
        "1640 ": "Rithy Cheng ",
        "2281 ": "Robert Geuggis ",
        "1473 ": "Robert Portmann ",
        "2448 ": "Robert Seiler ",
        "1927 ": "Roger Gubelmann ",
        "1629 ": "Roland H\u00e4berli ",
        "2332 ": "Roland Kuster ",
        "57 ": "Roland M\u00e4rki ",
        "2348 ": "Romaine Busato ",
        "2374 ": "Romana Saredi ",
        "2344 ": "Romana Taeuber ",
        "1790 ": "Romana Teauber ",
        "845 ": "Ronj Steffen ",
        "2249 ": "Rosa Achermann Hess ",
        "1531 ": "Rosa Dickreuter ",
        "2313 ": "Rosa Schneider ",
        "203 ": "Rose Crevoisier ",
        "898 ": "Rosmarie Kobel ",
        "983 ": "R\u00f6thlisberger Ines ",
        "2603 ": "Roxane Guillod ",
        "1913 ": "Ruth Amberg ",
        "1941 ": "Ruth Brechb\u00fchl ",
        "907 ": "Ruth B\u00fcrki ",
        "770 ": "Ruth Erhard ",
        "1655 ": "Ruth Frei ",
        "1454 ": "Ruth Frey ",
        "268 ": "Ruth Friedli ",
        "260 ": "Ruth Kurth ",
        "178 ": "Ruth Locher ",
        "2296 ": "Ruth M\u00fcller ",
        "1633 ": "Ruth Rutsch ",
        "876 ": "Ruth Schmid ",
        "2451 ": "Ruth Schneider ",
        "291 ": "Ruth Schwery ",
        "477 ": "Ruth Stepan ",
        "1131 ": "Ruth Wander ",
        "622 ": "Ruth W\u00fcthrich ",
        "493 ": "Sabina Danieli ",
        "1894 ": "Sabine Ecken ",
        "888 ": "Sabine Feller ",
        "1032 ": "Sabine Gresch ",
        "463 ": "Sabine Paolucci ",
        "1986 ": "Sabine Sch\u00fctz ",
        "2436 ": "Salome Schl\u00e4ppi-Berger ",
        "1691 ": "Samuel D\u00fcrr ",
        "1199 ": "Samuel Schmid ",
        "2364 ": "Sandra B\u00f6tschi ",
        "1889 ": "Sandra D\u00e4nzer ",
        "1192 ": "Sandra Etter ",
        "758 ": "Sandra Lehmann ",
        "1972 ": "Sandra Richard ",
        "1458 ": "Sandra Steuri-Werren ",
        "1586 ": "Sandra Wilkinson ",
        "2381 ": "Sandro Becher ",
        "195 ": "Sara Gygax Illien ",
        "2050 ": "Sara Meyer ",
        "2128 ": "Sarah Bolliger ",
        "2404 ": "Sarah Fischer ",
        "1639 ": "Sarah Hahn ",
        "2293 ": "Sarah Malerba ",
        "2150 ": "Selina Schmid ",
        "2353 ": "Severine Stein  -- Spitex Schweiz",
        "2125 ": "Sibel Gayret ",
        "1063 ": "Sibyl Matter ",
        "1973 ": "Sibylle Eicken ",
        "980 ": "Sibylle Felber ",
        "2014 ": "Sibylle H\u00e4nni ",
        "1661 ": "Sigrid Johner ",
        "1483 ": "Silvia Br\u00e4ndle ",
        "1724 ": "Silvia Briner ",
        "2385 ": "Silvia Gl\u00f6ckler ",
        "2336 ": "Silvia Greminger ",
        "1269 ": "Silvia Greminger ",
        "497 ": "Silvia Piva ",
        "271 ": "Silvia Racheter ",
        "298 ": "Silvia Spychiger ",
        "1196 ": "Silvia Tschumi ",
        "1626 ": "Silvia & Peter Michel ",
        "2535 ": "Simon Abenhaim ",
        "995 ": "Simon Rihs ",
        "1904 ": "Simone Dreier ",
        "2047 ": "Simone Gaberel ",
        "193 ": "Simone Hebeisen ",
        "1260 ": "Simone Kuhn ",
        "2263 ": "Simone Kunz ",
        "1520 ": "Simone Lehmann ",
        "1965 ": "Simone Mayor ",
        "2297 ": "Simone Schweizer ",
        "1807 ": "Simonetta Castelli ",
        "2373 ": "Sistina Furrer ",
        "1550 ": "Sonja Du\u00f2-Meyer ",
        "2216 ": "Sonja Reichen ",
        "1756 ": "Sonja Studer ",
        "1035 ": "Sophia Bohren ",
        "1646 ": "Sophie Markwalder ",
        "1134 ": "Sophie Rausis ",
        "2255 ": "Sophie Stockholm ",
        "2059 ": "Stefan Haemmig ",
        "1760 ": "Stefan Herrenschwand ",
        "261 ": "Stefan Leuenberger ",
        "1804 ": "Stefan M\u00fcnger ",
        "274 ": "Stefan R\u00e4z ",
        "1279 ": "Stefania Misteli ",
        "1066 ": "Stefano Consonni ",
        "1572 ": "Stefano Wenk ",
        "468 ": "Stephan Kormann ",
        "1818 ": "Stephanie von Roten ",
        "2089 ": "Sumie Woodtly ",
        "1283 ": "Suresh Suthesen ",
        "2624 ": "Susan Bernofski ",
        "1264 ": "Susan Steffen ",
        "1987 ": "Susann Schwenkel ",
        "1482 ": "Susanna Carigiet ",
        "1677 ": "Susanna Eicher ",
        "2131 ": "Susanna Miozzari ",
        "2471 ": "Susanna Reich ",
        "605 ": "Susanne Arnold ",
        "715 ": "Susanne Engel ",
        "684 ": "Susanne Furer ",
        "236 ": "Susanne Grosso ",
        "1611 ": "Susanne Gschwind ",
        "2497 ": "Susanne Lemberg ",
        "2454 ": "Susanne Oberli ",
        "1657 ": "Susanne Reber ",
        "1024 ": "Susanne Sturm Bosson ",
        "2136 ": "Susanne von Arb ",
        "2276 ": "Susanne Wullschleger ",
        "2396 ": "Susanne Zurbr\u00fcgg ",
        "1074 ": "Susi Andersson ",
        "2105 ": "Susi L\u00fcthi ",
        "74 ": "Suvana Iljos ",
        "606 ": "Suvarna Nussbaum ",
        "879 ": "Suzanne Jeanrichard ",
        "182 ": "Suzanne Morandi ",
        "2283 ": "Sven Heierli ",
        "535 ": "Sylvia Stutzmann ",
        "1943 ": "Tamara Mona ",
        "1645 ": "Tanja Kocher ",
        "1108 ": "Tanja Schupnek ",
        "2433 ": "Tanja und Simon Bovisi ",
        "918 ": "Tarja Hopf ",
        "2582 ": "Tatiana Quadri ",
        "699 ": "Telemaco Cesari ",
        "1940 ": "Teresa Gr\u00fctter ",
        "729 ": "Thea Flury ",
        "2004 ": "Thea Sonderegger ",
        "760 ": "Therese Bleifuss ",
        "2345 ": "Therese Friedli ",
        "1540 ": "Th\u00e9r\u00e8se Hadorn ",
        "2388 ": "Therese Huber ",
        "2389 ": "Therese Hubler ",
        "1888 ": "Therese Oehrli ",
        "1779 ": "Therese Steffen ",
        "1826 ": "Therese Sulzer ",
        "2302 ": "Therese Von Wattenwil ",
        "1680 ": "Therry Weibel ",
        "2233 ": "Thom Pfister ",
        "1180 ": "Thomas B\u00fcrki ",
        "470 ": "Thomas R\u00f6thlisberger ",
        "117 ": "Thomas Vonlanthen ",
        "1222 ": "Thomas W. Bechtler ",
        "1694 ": "Tim Hellstern ",
        "75 ": "Tina Laube ",
        "2420 ": "Tom Gnehm ",
        "1672 ": "Tom H\u00fcbner ",
        "1671 ": "Trant Gygi ",
        "1242 ": "Ueli Affolter ",
        "913 ": "Ueli Fuchser ",
        "932 ": "Ueli Matter ",
        "95 ": "Ueli Wyttenbach ",
        "1719 ": "Urban Novak ",
        "2168 ": "Urs Amsler ",
        "1876 ": "Urs Berner ",
        "640 ": "Urs Wettstein ",
        "1195 ": "Urs Daniel Laederach ",
        "687 ": "Urs Niklaus Marti ",
        "1952 ": "Ursina T\u00f6ndury ",
        "1147 ": "Ursula Augsburger ",
        "1443 ": "Ursula B\u00f6hm ",
        "2439 ": "Ursula Dellsperger ",
        "2011 ": "Ursula Freihofer ",
        "1087 ": "Ursula Funk Mordasini ",
        "464 ": "Ursula Gilgen ",
        "1471 ": "Ursula Hesterberg ",
        "625 ": "Ursula Jezler ",
        "162 ": "Ursula Kellerhals ",
        "1194 ": "Ursula Kern ",
        "1170 ": "Ursula Lemp ",
        "471 ": "Ursula L\u00fcscher ",
        "2194 ": "Ursula Mader ",
        "767 ": "Ursula Marti ",
        "1148 ": "Ursula Mock ",
        "1043 ": "Ursula Moser ",
        "1577 ": "Ursula M\u00fcnger ",
        "1693 ": "Ursula Neher ",
        "2299 ": "Ursula Perrelet ",
        "29 ": "Ursula R\u00f6thlisberger ",
        "1720 ": "Ursula Schneeberger ",
        "1277 ": "Ursula Schudel ",
        "198 ": "Ursula Staub ",
        "2123 ": "Ursula Thalmann ",
        "748 ": "Ursula von Gunten ",
        "1598 ": "Ursula Wyss ",
        "1740 ": "Ursula Zimmermann ",
        "248 ": "Ute Jenschke ",
        "2508 ": "Valentin Ritler ",
        "1991 ": "Valeria Corso ",
        "2537 ": "Val\u00e9rie Schelker ",
        "2117 ": "Valerio Brogini ",
        "1920 ": "Vanessa Sarbach ",
        "1514 ": "Vera Baumann ",
        "744 ": "Verena Egli ",
        "2350 ": "Verena Goldmann ",
        "2112 ": "Verena Heiniger ",
        "1557 ": "Verena Immenhauser ",
        "1421 ": "Verena Klauser ",
        "367 ": "Verena Laedrach-Feller ",
        "2284 ": "Verena Scheidegger ",
        "2413 ": "Verena Schmocker ",
        "2382 ": "Verena Strausak ",
        "1721 ": "Verena Wahli ",
        "503 ": "Veronika Grandjean ",
        "1999 ": "Veronika Huber ",
        "2294 ": "Veronika Z\u00fcrcher ",
        "1759 ": "Violetta Ameondola ",
        "135 ": "Vivian Spuhler ",
        "790 ": "Viviane Morard ",
        "1704 ": "Vreni Aebi ",
        "31 ": "Vreni Schmid ",
        "1800 ": "Vreni Weber ",
        "1182 ": "Walter Fruttiger ",
        "924 ": "Walter Spring ",
        "365 ": "Walter Thurnherr ",
        "773 ": "Waltraud Holtz-Honig ",
        "120 ": "Werner Stadelmann ",
        "1114 ": "Wilhelm zu Dohna ",
        "2141 ": "Wilhelm zu Dohna ",
        "871 ": "Willi Lanker ",
        "2361 ": "Wilma Ludwig ",
        "521 ": "Ysbeth Marcano ",
        "2333 ": "Yvonne Althaus ",
        "1895 ": "Yvonne Balsofiore ",
        "2217 ": "Yvonne Gempeler ",
        "1634 ": "Yvonne Schneider ",
        "1537 ": "Yvonne Vieli ",
        "1623 ": "Zara Nydegger "
    },
    "fieldName": "client",
    "defaultValue": "",
    "className": "form-control pz-form-widget client pz-error has-error",
    "appRootID": "APP-ID-7003-ECF1-97BD-DF32-EF05-120C-CB1A-6025",
    "placeholder": "Privat \/ Gesch\u00e4ftskunde",
    "ignoredKeySuffix": "@@@"
};